#ifndef GLEXT_EGL_H_
#define GLEXT_EGL_H_

#define GLEXT_EGL
#define GLEXT_OPTION_EGL_ALIAS
#define GLEXT_OPTION_EGL_LOADER

#ifdef __cplusplus
extern "C" {
#endif

#ifndef GLEXT_PLATFORM_H_
#define GLEXT_PLATFORM_H_

#ifndef GLEXT_PLATFORM_WIN32
#if defined(_WIN32) || defined(__WIN32__) || defined(WIN32)                   \
  || defined(__MINGW32__)
#define GLEXT_PLATFORM_WIN32 1
#else
#define GLEXT_PLATFORM_WIN32 0
#endif
#endif

#ifndef GLEXT_PLATFORM_APPLE
#ifdef __APPLE__
#define GLEXT_PLATFORM_APPLE 1
#else
#define GLEXT_PLATFORM_APPLE 0
#endif
#endif

#ifndef GLEXT_PLATFORM_EMSCRIPTEN
#ifdef __EMSCRIPTEN__
#define GLEXT_PLATFORM_EMSCRIPTEN 1
#else
#define GLEXT_PLATFORM_EMSCRIPTEN 0
#endif
#endif

#ifndef GLEXT_PLATFORM_UWP
#if defined(_MSC_VER) && !defined(GLEXT_INTERNAL_HAVE_WINAPIFAMILY)
#ifdef __has_include
#if __has_include(<winapifamily.h>)
#define GLEXT_INTERNAL_HAVE_WINAPIFAMILY 1
#endif
#elif _MSC_VER >= 1700 && !_USING_V110_SDK71_
#define GLEXT_INTERNAL_HAVE_WINAPIFAMILY 1
#endif
#endif

#ifdef GLEXT_INTERNAL_HAVE_WINAPIFAMILY
#include <winapifamily.h>
#if !WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)                        \
  && WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)
#define GLEXT_PLATFORM_UWP 1
#endif
#endif

#ifndef GLEXT_PLATFORM_UWP
#define GLEXT_PLATFORM_UWP 0
#endif
#endif

#ifdef __GNUC__
#define GLEXT_GNUC_EXTENSION __extension__
#else
#define GLEXT_GNUC_EXTENSION
#endif

#define GLEXT_UNUSED(x) (void)(x)

#ifndef GLEXT_API_CALL
#if defined(GLEXT_API_CALL_EXPORT)
#if GLEXT_PLATFORM_WIN32 || defined(__CYGWIN__)
#if defined(GLEXT_API_CALL_EXPORT_BUILD)
#if defined(__GNUC__)
#define GLEXT_API_CALL __attribute__ ((dllexport)) extern
#else
#define GLEXT_API_CALL __declspec (dllexport) extern
#endif
#else
#if defined(__GNUC__)
#define GLEXT_API_CALL __attribute__ ((dllimport)) extern
#else
#define GLEXT_API_CALL __declspec (dllimport) extern
#endif
#endif
#elif defined(__GNUC__) && defined(GLEXT_API_CALL_EXPORT_BUILD)
#define GLEXT_API_CALL __attribute__ ((visibility ("default"))) extern
#else
#define GLEXT_API_CALL extern
#endif
#else
#define GLEXT_API_CALL extern
#endif
#endif

#ifdef APIENTRY
#define GLEXT_API_PTR APIENTRY
#elif GLEXT_PLATFORM_WIN32
#define GLEXT_API_PTR __stdcall
#else
#define GLEXT_API_PTR
#endif

#ifndef GLAPI
#define GLAPI GLEXT_API_CALL
#endif

#ifndef GLAPIENTRY
#define GLAPIENTRY GLEXT_API_PTR
#endif

#define GLEXT_MAKE_VERSION(major, minor) (major * 10000 + minor)
#define GLEXT_VERSION_MAJOR(version) (version / 10000)
#define GLEXT_VERSION_MINOR(version) (version % 10000)

#define GLEXT_GENERATOR_VERSION "2.0.8"

typedef void (*GLEXTapiproc) (void);

typedef GLEXTapiproc (*GLEXTloadfunc) (const char* name);
typedef GLEXTapiproc (*GLEXTuserptrloadfunc) (void* userptr, const char* name);

typedef void (*GLEXTprecallback) (const char* name, GLEXTapiproc apiproc,
                                  int len_args, ...);
typedef void (*GLEXTpostcallback) (void* ret, const char* name,
                                   GLEXTapiproc apiproc, int len_args, ...);

#endif /* GLEXT_PLATFORM_H_ */

#define EGL_ALLOC_NEW_DISPLAY_EXT 0x3379
#define EGL_ALPHA_FORMAT 0x3088
#define EGL_ALPHA_FORMAT_NONPRE 0x308B
#define EGL_ALPHA_FORMAT_PRE 0x308C
#define EGL_ALPHA_MASK_SIZE 0x303E
#define EGL_ALPHA_SIZE 0x3021
#define EGL_ALREADY_SIGNALED_NV 0x30EA
#define EGL_AUTO_STEREO_NV 0x3136
#define EGL_BACK_BUFFER 0x3084
#define EGL_BAD_ACCESS 0x3002
#define EGL_BAD_ALLOC 0x3003
#define EGL_BAD_ATTRIBUTE 0x3004
#define EGL_BAD_CONFIG 0x3005
#define EGL_BAD_CONTEXT 0x3006
#define EGL_BAD_CURRENT_SURFACE 0x3007
#define EGL_BAD_DEVICE_EXT 0x322B
#define EGL_BAD_DISPLAY 0x3008
#define EGL_BAD_MATCH 0x3009
#define EGL_BAD_NATIVE_PIXMAP 0x300A
#define EGL_BAD_NATIVE_WINDOW 0x300B
#define EGL_BAD_OUTPUT_LAYER_EXT 0x322D
#define EGL_BAD_OUTPUT_PORT_EXT 0x322E
#define EGL_BAD_PARAMETER 0x300C
#define EGL_BAD_STATE_KHR 0x321C
#define EGL_BAD_STREAM_KHR 0x321B
#define EGL_BAD_SURFACE 0x300D
#define EGL_BIND_TO_TEXTURE_RGB 0x3039
#define EGL_BIND_TO_TEXTURE_RGBA 0x303A
#define EGL_BITMAP_ORIGIN_KHR 0x30C8
#define EGL_BITMAP_PITCH_KHR 0x30C7
#define EGL_BITMAP_PIXEL_ALPHA_OFFSET_KHR 0x30CC
#define EGL_BITMAP_PIXEL_BLUE_OFFSET_KHR 0x30CB
#define EGL_BITMAP_PIXEL_GREEN_OFFSET_KHR 0x30CA
#define EGL_BITMAP_PIXEL_LUMINANCE_OFFSET_KHR 0x30CD
#define EGL_BITMAP_PIXEL_RED_OFFSET_KHR 0x30C9
#define EGL_BITMAP_PIXEL_SIZE_KHR 0x3110
#define EGL_BITMAP_POINTER_KHR 0x30C6
#define EGL_BLUE_SIZE 0x3022
#define EGL_BOTTOM_NV 0x336E
#define EGL_BUFFER_AGE_EXT 0x313D
#define EGL_BUFFER_AGE_KHR 0x313D
#define EGL_BUFFER_DESTROYED 0x3095
#define EGL_BUFFER_PRESERVED 0x3094
#define EGL_BUFFER_SIZE 0x3020
#define EGL_CLIENT_APIS 0x308D
#define EGL_CLIENT_PIXMAP_POINTER_HI 0x8F74
#define EGL_CL_EVENT_HANDLE 0x309C
#define EGL_CL_EVENT_HANDLE_KHR 0x309C
#define EGL_COLORSPACE 0x3087
#define EGL_COLORSPACE_LINEAR 0x308A
#define EGL_COLORSPACE_sRGB 0x3089
#define EGL_COLOR_ARGB_HI 0x8F73
#define EGL_COLOR_BUFFER_TYPE 0x303F
#define EGL_COLOR_COMPONENT_TYPE_EXT 0x3339
#define EGL_COLOR_COMPONENT_TYPE_FIXED_EXT 0x333A
#define EGL_COLOR_COMPONENT_TYPE_FLOAT_EXT 0x333B
#define EGL_COLOR_COMPONENT_TYPE_INTEGER_ARM 0x3288
#define EGL_COLOR_COMPONENT_TYPE_UNSIGNED_INTEGER_ARM 0x3287
#define EGL_COLOR_FORMAT_HI 0x8F70
#define EGL_COLOR_RGBA_HI 0x8F72
#define EGL_COLOR_RGB_HI 0x8F71
#define EGL_COMPOSITE_DEADLINE_ANDROID 0x3431
#define EGL_COMPOSITE_INTERVAL_ANDROID 0x3432
#define EGL_COMPOSITE_TO_PRESENT_LATENCY_ANDROID 0x3433
#define EGL_COMPOSITION_LATCH_TIME_ANDROID 0x3436
#define EGL_COMPOSITOR_DROP_NEWEST_FRAME_EXT 0x3462
#define EGL_COMPOSITOR_KEEP_NEWEST_FRAME_EXT 0x3463
#define EGL_CONDITION_SATISFIED 0x30F6
#define EGL_CONDITION_SATISFIED_KHR 0x30F6
#define EGL_CONDITION_SATISFIED_NV 0x30EC
#define EGL_CONFIG_CAVEAT 0x3027
#define EGL_CONFIG_ID 0x3028
#define EGL_CONFIG_SELECT_GROUP_EXT 0x34C0
#define EGL_CONFORMANT 0x3042
#define EGL_CONFORMANT_KHR 0x3042
#define EGL_CONSUMER_ACQUIRE_TIMEOUT_USEC_KHR 0x321E
#define EGL_CONSUMER_AUTO_ORIENTATION_NV 0x3369
#define EGL_CONSUMER_FRAME_KHR 0x3213
#define EGL_CONSUMER_LATENCY_USEC_KHR 0x3210
#define EGL_CONSUMER_MAX_FRAME_HINT_NV 0x3338
#define EGL_CONSUMER_METADATA_NV 0x3254
#define EGL_CONTEXT_CLIENT_TYPE 0x3097
#define EGL_CONTEXT_CLIENT_VERSION 0x3098
#define EGL_CONTEXT_FLAGS_KHR 0x30FC
#define EGL_CONTEXT_LOST 0x300E
#define EGL_CONTEXT_MAJOR_VERSION 0x3098
#define EGL_CONTEXT_MAJOR_VERSION_KHR 0x3098
#define EGL_CONTEXT_MINOR_VERSION 0x30FB
#define EGL_CONTEXT_MINOR_VERSION_KHR 0x30FB
#define EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT 0x00000002
#define EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT_KHR 0x00000002
#define EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT 0x00000001
#define EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT_KHR 0x00000001
#define EGL_CONTEXT_OPENGL_DEBUG 0x31B0
#define EGL_CONTEXT_OPENGL_DEBUG_BIT_KHR 0x00000001
#define EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE 0x31B1
#define EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE_BIT_KHR 0x00000002
#define EGL_CONTEXT_OPENGL_NO_ERROR_KHR 0x31B3
#define EGL_CONTEXT_OPENGL_PROFILE_MASK 0x30FD
#define EGL_CONTEXT_OPENGL_PROFILE_MASK_KHR 0x30FD
#define EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY 0x31BD
#define EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_EXT 0x3138
#define EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_KHR 0x31BD
#define EGL_CONTEXT_OPENGL_ROBUST_ACCESS 0x31B2
#define EGL_CONTEXT_OPENGL_ROBUST_ACCESS_BIT_KHR 0x00000004
#define EGL_CONTEXT_OPENGL_ROBUST_ACCESS_EXT 0x30BF
#define EGL_CONTEXT_PRIORITY_HIGH_IMG 0x3101
#define EGL_CONTEXT_PRIORITY_LEVEL_IMG 0x3100
#define EGL_CONTEXT_PRIORITY_LOW_IMG 0x3103
#define EGL_CONTEXT_PRIORITY_MEDIUM_IMG 0x3102
#define EGL_CONTEXT_PRIORITY_REALTIME_NV 0x3357
#define EGL_CONTEXT_RELEASE_BEHAVIOR_FLUSH_KHR 0x2098
#define EGL_CONTEXT_RELEASE_BEHAVIOR_KHR 0x2097
#define EGL_CONTEXT_RELEASE_BEHAVIOR_NONE_KHR 0
#define EGL_CORE_NATIVE_ENGINE 0x305B
#define EGL_COVERAGE_BUFFERS_NV 0x30E0
#define EGL_COVERAGE_SAMPLES_NV 0x30E1
#define EGL_COVERAGE_SAMPLE_RESOLVE_DEFAULT_NV 0x3132
#define EGL_COVERAGE_SAMPLE_RESOLVE_NONE_NV 0x3133
#define EGL_COVERAGE_SAMPLE_RESOLVE_NV 0x3131
#define EGL_CTA861_3_MAX_CONTENT_LIGHT_LEVEL_EXT 0x3360
#define EGL_CTA861_3_MAX_FRAME_AVERAGE_LEVEL_EXT 0x3361
#define EGL_CUDA_DEVICE_NV 0x323A
#define EGL_CUDA_EVENT_HANDLE_NV 0x323B
#define EGL_D3D11_DEVICE_ANGLE 0x33A1
#define EGL_D3D9_DEVICE_ANGLE 0x33A0
#define EGL_D3D_TEXTURE_2D_SHARE_HANDLE_ANGLE 0x3200
#define EGL_DEBUG_CALLBACK_KHR 0x33B8
#define EGL_DEBUG_MSG_CRITICAL_KHR 0x33B9
#define EGL_DEBUG_MSG_ERROR_KHR 0x33BA
#define EGL_DEBUG_MSG_INFO_KHR 0x33BC
#define EGL_DEBUG_MSG_WARN_KHR 0x33BB
#define EGL_DEFAULT_DISPLAY EGL_CAST (EGLNativeDisplayType, 0)
#define EGL_DEPTH_ENCODING_NONE_NV 0
#define EGL_DEPTH_ENCODING_NONLINEAR_NV 0x30E3
#define EGL_DEPTH_ENCODING_NV 0x30E2
#define EGL_DEPTH_SIZE 0x3025
#define EGL_DEQUEUE_READY_TIME_ANDROID 0x343B
#define EGL_DEVICE_EXT 0x322C
#define EGL_DEVICE_TYPE_CPU_EXT 0x3594
#define EGL_DEVICE_TYPE_DISCRETE_GPU_EXT 0x3593
#define EGL_DEVICE_TYPE_EXT 0x3590
#define EGL_DEVICE_TYPE_INTEGRATED_GPU_EXT 0x3592
#define EGL_DEVICE_TYPE_OTHER_EXT 0x3591
#define EGL_DEVICE_UUID_EXT 0x335C
#define EGL_DISCARD_SAMPLES_ARM 0x3286
#define EGL_DISPLAY_PRESENT_TIME_ANDROID 0x343A
#define EGL_DISPLAY_SCALING 10000
#define EGL_DMA_BUF_PLANE0_FD_EXT 0x3272
#define EGL_DMA_BUF_PLANE0_MODIFIER_HI_EXT 0x3444
#define EGL_DMA_BUF_PLANE0_MODIFIER_LO_EXT 0x3443
#define EGL_DMA_BUF_PLANE0_OFFSET_EXT 0x3273
#define EGL_DMA_BUF_PLANE0_PITCH_EXT 0x3274
#define EGL_DMA_BUF_PLANE1_FD_EXT 0x3275
#define EGL_DMA_BUF_PLANE1_MODIFIER_HI_EXT 0x3446
#define EGL_DMA_BUF_PLANE1_MODIFIER_LO_EXT 0x3445
#define EGL_DMA_BUF_PLANE1_OFFSET_EXT 0x3276
#define EGL_DMA_BUF_PLANE1_PITCH_EXT 0x3277
#define EGL_DMA_BUF_PLANE2_FD_EXT 0x3278
#define EGL_DMA_BUF_PLANE2_MODIFIER_HI_EXT 0x3448
#define EGL_DMA_BUF_PLANE2_MODIFIER_LO_EXT 0x3447
#define EGL_DMA_BUF_PLANE2_OFFSET_EXT 0x3279
#define EGL_DMA_BUF_PLANE2_PITCH_EXT 0x327A
#define EGL_DMA_BUF_PLANE3_FD_EXT 0x3440
#define EGL_DMA_BUF_PLANE3_MODIFIER_HI_EXT 0x344A
#define EGL_DMA_BUF_PLANE3_MODIFIER_LO_EXT 0x3449
#define EGL_DMA_BUF_PLANE3_OFFSET_EXT 0x3441
#define EGL_DMA_BUF_PLANE3_PITCH_EXT 0x3442
#define EGL_DONT_CARE EGL_CAST (EGLint, -1)
#define EGL_DRAW 0x3059
#define EGL_DRIVER_NAME_EXT 0x335E
#define EGL_DRIVER_UUID_EXT 0x335D
#define EGL_DRM_BUFFER_FORMAT_ARGB32_MESA 0x31D2
#define EGL_DRM_BUFFER_FORMAT_MESA 0x31D0
#define EGL_DRM_BUFFER_MESA 0x31D3
#define EGL_DRM_BUFFER_STRIDE_MESA 0x31D4
#define EGL_DRM_BUFFER_USE_CURSOR_MESA 0x00000004
#define EGL_DRM_BUFFER_USE_MESA 0x31D1
#define EGL_DRM_BUFFER_USE_SCANOUT_MESA 0x00000001
#define EGL_DRM_BUFFER_USE_SHARE_MESA 0x00000002
#define EGL_DRM_CONNECTOR_EXT 0x3236
#define EGL_DRM_CRTC_EXT 0x3234
#define EGL_DRM_DEVICE_FILE_EXT 0x3233
#define EGL_DRM_MASTER_FD_EXT 0x333C
#define EGL_DRM_PLANE_EXT 0x3235
#define EGL_DRM_RENDER_NODE_FILE_EXT 0x3377
#define EGL_EXTENSIONS 0x3055
#define EGL_EXTERNAL_REF_ID_EXT 0x3461
#define EGL_FALSE 0
#define EGL_FIRST_COMPOSITION_GPU_FINISHED_TIME_ANDROID 0x3439
#define EGL_FIRST_COMPOSITION_START_TIME_ANDROID 0x3437
#define EGL_FIXED_SIZE_ANGLE 0x3201
#define EGL_FOREVER 0xFFFFFFFFFFFFFFFF
#define EGL_FOREVER_KHR 0xFFFFFFFFFFFFFFFF
#define EGL_FOREVER_NV 0xFFFFFFFFFFFFFFFF
#define EGL_FORMAT_RGBA_8888_EXACT_KHR 0x30C2
#define EGL_FORMAT_RGBA_8888_KHR 0x30C3
#define EGL_FORMAT_RGB_565_EXACT_KHR 0x30C0
#define EGL_FORMAT_RGB_565_KHR 0x30C1
#define EGL_FRAMEBUFFER_TARGET_ANDROID 0x3147
#define EGL_FRONT_BUFFER_AUTO_REFRESH_ANDROID 0x314C
#define EGL_FRONT_BUFFER_EXT 0x3464
#define EGL_GENERATE_RESET_ON_VIDEO_MEMORY_PURGE_NV 0x334C
#define EGL_GL_COLORSPACE 0x309D
#define EGL_GL_COLORSPACE_BT2020_HLG_EXT 0x3540
#define EGL_GL_COLORSPACE_BT2020_LINEAR_EXT 0x333F
#define EGL_GL_COLORSPACE_BT2020_PQ_EXT 0x3340
#define EGL_GL_COLORSPACE_DEFAULT_EXT 0x314D
#define EGL_GL_COLORSPACE_DISPLAY_P3_EXT 0x3363
#define EGL_GL_COLORSPACE_DISPLAY_P3_LINEAR_EXT 0x3362
#define EGL_GL_COLORSPACE_DISPLAY_P3_PASSTHROUGH_EXT 0x3490
#define EGL_GL_COLORSPACE_KHR 0x309D
#define EGL_GL_COLORSPACE_LINEAR 0x308A
#define EGL_GL_COLORSPACE_LINEAR_KHR 0x308A
#define EGL_GL_COLORSPACE_SCRGB_EXT 0x3351
#define EGL_GL_COLORSPACE_SCRGB_LINEAR_EXT 0x3350
#define EGL_GL_COLORSPACE_SRGB 0x3089
#define EGL_GL_COLORSPACE_SRGB_KHR 0x3089
#define EGL_GL_RENDERBUFFER 0x30B9
#define EGL_GL_RENDERBUFFER_KHR 0x30B9
#define EGL_GL_TEXTURE_2D 0x30B1
#define EGL_GL_TEXTURE_2D_KHR 0x30B1
#define EGL_GL_TEXTURE_3D 0x30B2
#define EGL_GL_TEXTURE_3D_KHR 0x30B2
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X 0x30B4
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X_KHR 0x30B4
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y 0x30B6
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y_KHR 0x30B6
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z 0x30B8
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z_KHR 0x30B8
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X 0x30B3
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X_KHR 0x30B3
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y 0x30B5
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y_KHR 0x30B5
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z 0x30B7
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z_KHR 0x30B7
#define EGL_GL_TEXTURE_LEVEL 0x30BC
#define EGL_GL_TEXTURE_LEVEL_KHR 0x30BC
#define EGL_GL_TEXTURE_ZOFFSET 0x30BD
#define EGL_GL_TEXTURE_ZOFFSET_KHR 0x30BD
#define EGL_GREEN_SIZE 0x3023
#define EGL_HEIGHT 0x3056
#define EGL_HORIZONTAL_RESOLUTION 0x3090
#define EGL_IMAGE_PRESERVED 0x30D2
#define EGL_IMAGE_PRESERVED_KHR 0x30D2
#define EGL_IMPORT_EXPLICIT_SYNC_EXT 0x3472
#define EGL_IMPORT_IMPLICIT_SYNC_EXT 0x3471
#define EGL_IMPORT_SYNC_TYPE_EXT 0x3470
#define EGL_ITU_REC2020_EXT 0x3281
#define EGL_ITU_REC601_EXT 0x327F
#define EGL_ITU_REC709_EXT 0x3280
#define EGL_LARGEST_PBUFFER 0x3058
#define EGL_LAST_COMPOSITION_START_TIME_ANDROID 0x3438
#define EGL_LEFT_NV 0x336B
#define EGL_LEVEL 0x3029
#define EGL_LINUX_DMA_BUF_EXT 0x3270
#define EGL_LINUX_DRM_FOURCC_EXT 0x3271
#define EGL_LOCK_SURFACE_BIT_KHR 0x0080
#define EGL_LOCK_USAGE_HINT_KHR 0x30C5
#define EGL_LOSE_CONTEXT_ON_RESET 0x31BF
#define EGL_LOSE_CONTEXT_ON_RESET_EXT 0x31BF
#define EGL_LOSE_CONTEXT_ON_RESET_KHR 0x31BF
#define EGL_LOWER_LEFT_KHR 0x30CE
#define EGL_LUMINANCE_BUFFER 0x308F
#define EGL_LUMINANCE_SIZE 0x303D
#define EGL_MAP_PRESERVE_PIXELS_KHR 0x30C4
#define EGL_MATCH_FORMAT_KHR 0x3043
#define EGL_MATCH_NATIVE_PIXMAP 0x3041
#define EGL_MAX_PBUFFER_HEIGHT 0x302A
#define EGL_MAX_PBUFFER_PIXELS 0x302B
#define EGL_MAX_PBUFFER_WIDTH 0x302C
#define EGL_MAX_STREAM_METADATA_BLOCKS_NV 0x3250
#define EGL_MAX_STREAM_METADATA_BLOCK_SIZE_NV 0x3251
#define EGL_MAX_STREAM_METADATA_TOTAL_SIZE_NV 0x3252
#define EGL_MAX_SWAP_INTERVAL 0x303C
#define EGL_METADATA0_SIZE_NV 0x3255
#define EGL_METADATA0_TYPE_NV 0x3259
#define EGL_METADATA1_SIZE_NV 0x3256
#define EGL_METADATA1_TYPE_NV 0x325A
#define EGL_METADATA2_SIZE_NV 0x3257
#define EGL_METADATA2_TYPE_NV 0x325B
#define EGL_METADATA3_SIZE_NV 0x3258
#define EGL_METADATA3_TYPE_NV 0x325C
#define EGL_METADATA_SCALING_EXT 50000
#define EGL_MIN_SWAP_INTERVAL 0x303B
#define EGL_MIPMAP_LEVEL 0x3083
#define EGL_MIPMAP_TEXTURE 0x3082
#define EGL_MULTISAMPLE_RESOLVE 0x3099
#define EGL_MULTISAMPLE_RESOLVE_BOX 0x309B
#define EGL_MULTISAMPLE_RESOLVE_BOX_BIT 0x0200
#define EGL_MULTISAMPLE_RESOLVE_DEFAULT 0x309A
#define EGL_MULTIVIEW_VIEW_COUNT_EXT 0x3134
#define EGL_MUTABLE_RENDER_BUFFER_BIT_KHR 0x1000
#define EGL_NATIVE_BUFFER_ANDROID 0x3140
#define EGL_NATIVE_BUFFER_MULTIPLANE_SEPARATE_IMG 0x3105
#define EGL_NATIVE_BUFFER_PLANE_OFFSET_IMG 0x3106
#define EGL_NATIVE_BUFFER_QNX 0x3551
#define EGL_NATIVE_BUFFER_TIZEN 0x32A0
#define EGL_NATIVE_BUFFER_USAGE_ANDROID 0x3143
#define EGL_NATIVE_BUFFER_USAGE_PROTECTED_BIT_ANDROID 0x00000001
#define EGL_NATIVE_BUFFER_USAGE_RENDERBUFFER_BIT_ANDROID 0x00000002
#define EGL_NATIVE_BUFFER_USAGE_TEXTURE_BIT_ANDROID 0x00000004
#define EGL_NATIVE_PIXMAP_KHR 0x30B0
#define EGL_NATIVE_RENDERABLE 0x302D
#define EGL_NATIVE_SURFACE_TIZEN 0x32A1
#define EGL_NATIVE_VISUAL_ID 0x302E
#define EGL_NATIVE_VISUAL_TYPE 0x302F
#define EGL_NONE 0x3038
#define EGL_NON_CONFORMANT_CONFIG 0x3051
#define EGL_NOT_INITIALIZED 0x3001
#define EGL_NO_CONFIG_KHR EGL_CAST (EGLConfig, 0)
#define EGL_NO_CONTEXT EGL_CAST (EGLContext, 0)
#define EGL_NO_DEVICE_EXT EGL_CAST (EGLDeviceEXT, 0)
#define EGL_NO_DISPLAY EGL_CAST (EGLDisplay, 0)
#define EGL_NO_FILE_DESCRIPTOR_KHR EGL_CAST (EGLNativeFileDescriptorKHR, -1)
#define EGL_NO_IMAGE EGL_CAST (EGLImage, 0)
#define EGL_NO_IMAGE_KHR EGL_CAST (EGLImageKHR, 0)
#define EGL_NO_NATIVE_FENCE_FD_ANDROID -1
#define EGL_NO_OUTPUT_LAYER_EXT EGL_CAST (EGLOutputLayerEXT, 0)
#define EGL_NO_OUTPUT_PORT_EXT EGL_CAST (EGLOutputPortEXT, 0)
#define EGL_NO_RESET_NOTIFICATION 0x31BE
#define EGL_NO_RESET_NOTIFICATION_EXT 0x31BE
#define EGL_NO_RESET_NOTIFICATION_KHR 0x31BE
#define EGL_NO_STREAM_KHR EGL_CAST (EGLStreamKHR, 0)
#define EGL_NO_SURFACE EGL_CAST (EGLSurface, 0)
#define EGL_NO_SYNC EGL_CAST (EGLSync, 0)
#define EGL_NO_SYNC_KHR EGL_CAST (EGLSync, 0)
#define EGL_NO_SYNC_NV EGL_CAST (EGLSync, 0)
#define EGL_NO_TEXTURE 0x305C
#define EGL_OBJECT_CONTEXT_KHR 0x33B2
#define EGL_OBJECT_DISPLAY_KHR 0x33B1
#define EGL_OBJECT_IMAGE_KHR 0x33B4
#define EGL_OBJECT_STREAM_KHR 0x33B6
#define EGL_OBJECT_SURFACE_KHR 0x33B3
#define EGL_OBJECT_SYNC_KHR 0x33B5
#define EGL_OBJECT_THREAD_KHR 0x33B0
#define EGL_OPENGL_API 0x30A2
#define EGL_OPENGL_BIT 0x0008
#define EGL_OPENGL_ES2_BIT 0x0004
#define EGL_OPENGL_ES3_BIT 0x00000040
#define EGL_OPENGL_ES3_BIT_KHR 0x00000040
#define EGL_OPENGL_ES_API 0x30A0
#define EGL_OPENGL_ES_BIT 0x0001
#define EGL_OPENVG_API 0x30A1
#define EGL_OPENVG_BIT 0x0002
#define EGL_OPENVG_IMAGE 0x3096
#define EGL_OPENWF_DEVICE_EXT 0x333D
#define EGL_OPENWF_DEVICE_ID_EXT 0x3237
#define EGL_OPENWF_PIPELINE_ID_EXT 0x3238
#define EGL_OPENWF_PORT_ID_EXT 0x3239
#define EGL_OPTIMAL_FORMAT_BIT_KHR 0x0100
#define EGL_PBUFFER_BIT 0x0001
#define EGL_PENDING_FRAME_NV 0x3329
#define EGL_PENDING_METADATA_NV 0x3328
#define EGL_PIXEL_ASPECT_RATIO 0x3092
#define EGL_PIXMAP_BIT 0x0002
#define EGL_PLATFORM_ANDROID_KHR 0x3141
#define EGL_PLATFORM_DEVICE_EXT 0x313F
#define EGL_PLATFORM_GBM_KHR 0x31D7
#define EGL_PLATFORM_GBM_MESA 0x31D7
#define EGL_PLATFORM_SCREEN_QNX 0x3550
#define EGL_PLATFORM_SURFACELESS_MESA 0x31DD
#define EGL_PLATFORM_WAYLAND_EXT 0x31D8
#define EGL_PLATFORM_WAYLAND_KHR 0x31D8
#define EGL_PLATFORM_X11_EXT 0x31D5
#define EGL_PLATFORM_X11_KHR 0x31D5
#define EGL_PLATFORM_X11_SCREEN_EXT 0x31D6
#define EGL_PLATFORM_X11_SCREEN_KHR 0x31D6
#define EGL_PLATFORM_XCB_EXT 0x31DC
#define EGL_PLATFORM_XCB_SCREEN_EXT 0x31DE
#define EGL_POST_SUB_BUFFER_SUPPORTED_NV 0x30BE
#define EGL_PRESENT_OPAQUE_EXT 0x31DF
#define EGL_PRIMARY_COMPOSITOR_CONTEXT_EXT 0x3460
#define EGL_PRODUCER_AUTO_ORIENTATION_NV 0x336A
#define EGL_PRODUCER_FRAME_KHR 0x3212
#define EGL_PRODUCER_MAX_FRAME_HINT_NV 0x3337
#define EGL_PRODUCER_METADATA_NV 0x3253
#define EGL_PROTECTED_CONTENT_EXT 0x32C0
#define EGL_QUADRUPLE_BUFFER_NV 0x3231
#define EGL_READ 0x305A
#define EGL_READS_DONE_TIME_ANDROID 0x343C
#define EGL_READ_SURFACE_BIT_KHR 0x0001
#define EGL_RECORDABLE_ANDROID 0x3142
#define EGL_RED_SIZE 0x3024
#define EGL_RENDERABLE_TYPE 0x3040
#define EGL_RENDERER_EXT 0x335F
#define EGL_RENDERING_COMPLETE_TIME_ANDROID 0x3435
#define EGL_RENDER_BUFFER 0x3086
#define EGL_REQUESTED_PRESENT_TIME_ANDROID 0x3434
#define EGL_RGB_BUFFER 0x308E
#define EGL_RIGHT_NV 0x336C
#define EGL_SAMPLES 0x3031
#define EGL_SAMPLE_BUFFERS 0x3032
#define EGL_SAMPLE_RANGE_HINT_EXT 0x327C
#define EGL_SIGNALED 0x30F2
#define EGL_SIGNALED_KHR 0x30F2
#define EGL_SIGNALED_NV 0x30E8
#define EGL_SINGLE_BUFFER 0x3085
#define EGL_SLOW_CONFIG 0x3050
#define EGL_SMPTE2086_DISPLAY_PRIMARY_BX_EXT 0x3345
#define EGL_SMPTE2086_DISPLAY_PRIMARY_BY_EXT 0x3346
#define EGL_SMPTE2086_DISPLAY_PRIMARY_GX_EXT 0x3343
#define EGL_SMPTE2086_DISPLAY_PRIMARY_GY_EXT 0x3344
#define EGL_SMPTE2086_DISPLAY_PRIMARY_RX_EXT 0x3341
#define EGL_SMPTE2086_DISPLAY_PRIMARY_RY_EXT 0x3342
#define EGL_SMPTE2086_MAX_LUMINANCE_EXT 0x3349
#define EGL_SMPTE2086_MIN_LUMINANCE_EXT 0x334A
#define EGL_SMPTE2086_WHITE_POINT_X_EXT 0x3347
#define EGL_SMPTE2086_WHITE_POINT_Y_EXT 0x3348
#define EGL_SOCKET_HANDLE_NV 0x324C
#define EGL_SOCKET_TYPE_INET_NV 0x324F
#define EGL_SOCKET_TYPE_NV 0x324D
#define EGL_SOCKET_TYPE_UNIX_NV 0x324E
#define EGL_STENCIL_SIZE 0x3026
#define EGL_STREAM_BIT_KHR 0x0800
#define EGL_STREAM_CONSUMER_IMAGE_NV 0x3373
#define EGL_STREAM_CONSUMER_IMAGE_USE_SCANOUT_NV 0x3378
#define EGL_STREAM_CONSUMER_NV 0x3248
#define EGL_STREAM_CROSS_DISPLAY_NV 0x334E
#define EGL_STREAM_CROSS_OBJECT_NV 0x334D
#define EGL_STREAM_CROSS_PARTITION_NV 0x323F
#define EGL_STREAM_CROSS_PROCESS_NV 0x3245
#define EGL_STREAM_CROSS_SYSTEM_NV 0x334F
#define EGL_STREAM_DMA_NV 0x3371
#define EGL_STREAM_DMA_SERVER_NV 0x3372
#define EGL_STREAM_ENDPOINT_NV 0x3243
#define EGL_STREAM_FIFO_LENGTH_KHR 0x31FC
#define EGL_STREAM_FIFO_SYNCHRONOUS_NV 0x3336
#define EGL_STREAM_FRAME_MAJOR_AXIS_NV 0x3368
#define EGL_STREAM_FRAME_ORIGIN_X_NV 0x3366
#define EGL_STREAM_FRAME_ORIGIN_Y_NV 0x3367
#define EGL_STREAM_IMAGE_ADD_NV 0x3374
#define EGL_STREAM_IMAGE_AVAILABLE_NV 0x3376
#define EGL_STREAM_IMAGE_REMOVE_NV 0x3375
#define EGL_STREAM_LOCAL_NV 0x3244
#define EGL_STREAM_PRODUCER_NV 0x3247
#define EGL_STREAM_PROTOCOL_FD_NV 0x3246
#define EGL_STREAM_PROTOCOL_NV 0x3242
#define EGL_STREAM_PROTOCOL_SOCKET_NV 0x324B
#define EGL_STREAM_STATE_CONNECTING_KHR 0x3216
#define EGL_STREAM_STATE_CREATED_KHR 0x3215
#define EGL_STREAM_STATE_DISCONNECTED_KHR 0x321A
#define EGL_STREAM_STATE_EMPTY_KHR 0x3217
#define EGL_STREAM_STATE_INITIALIZING_NV 0x3240
#define EGL_STREAM_STATE_KHR 0x3214
#define EGL_STREAM_STATE_NEW_FRAME_AVAILABLE_KHR 0x3218
#define EGL_STREAM_STATE_OLD_FRAME_AVAILABLE_KHR 0x3219
#define EGL_STREAM_TIME_CONSUMER_KHR 0x31FE
#define EGL_STREAM_TIME_NOW_KHR 0x31FD
#define EGL_STREAM_TIME_PENDING_NV 0x332A
#define EGL_STREAM_TIME_PRODUCER_KHR 0x31FF
#define EGL_STREAM_TYPE_NV 0x3241
#define EGL_SUCCESS 0x3000
#define EGL_SUPPORT_RESET_NV 0x3334
#define EGL_SUPPORT_REUSE_NV 0x3335
#define EGL_SURFACE_COMPRESSION_EXT 0x34B0
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_10BPC_EXT 0x34BD
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_11BPC_EXT 0x34BE
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_12BPC_EXT 0x34BF
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_1BPC_EXT 0x34B4
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_2BPC_EXT 0x34B5
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_3BPC_EXT 0x34B6
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_4BPC_EXT 0x34B7
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_5BPC_EXT 0x34B8
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_6BPC_EXT 0x34B9
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_7BPC_EXT 0x34BA
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_8BPC_EXT 0x34BB
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_9BPC_EXT 0x34BC
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_DEFAULT_EXT 0x34B2
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_NONE_EXT 0x34B1
#define EGL_SURFACE_COMPRESSION_PLANE1_EXT 0x328E
#define EGL_SURFACE_COMPRESSION_PLANE2_EXT 0x328F
#define EGL_SURFACE_TYPE 0x3033
#define EGL_SWAP_BEHAVIOR 0x3093
#define EGL_SWAP_BEHAVIOR_PRESERVED_BIT 0x0400
#define EGL_SWAP_INTERVAL_EXT 0x322F
#define EGL_SYNC_CLIENT_EXT 0x3364
#define EGL_SYNC_CLIENT_SIGNAL_EXT 0x3365
#define EGL_SYNC_CL_EVENT 0x30FE
#define EGL_SYNC_CL_EVENT_COMPLETE 0x30FF
#define EGL_SYNC_CL_EVENT_COMPLETE_KHR 0x30FF
#define EGL_SYNC_CL_EVENT_KHR 0x30FE
#define EGL_SYNC_CONDITION 0x30F8
#define EGL_SYNC_CONDITION_KHR 0x30F8
#define EGL_SYNC_CONDITION_NV 0x30EE
#define EGL_SYNC_CUDA_EVENT_COMPLETE_NV 0x323D
#define EGL_SYNC_CUDA_EVENT_NV 0x323C
#define EGL_SYNC_FENCE 0x30F9
#define EGL_SYNC_FENCE_KHR 0x30F9
#define EGL_SYNC_FENCE_NV 0x30EF
#define EGL_SYNC_FLUSH_COMMANDS_BIT 0x0001
#define EGL_SYNC_FLUSH_COMMANDS_BIT_KHR 0x0001
#define EGL_SYNC_FLUSH_COMMANDS_BIT_NV 0x0001
#define EGL_SYNC_NATIVE_FENCE_ANDROID 0x3144
#define EGL_SYNC_NATIVE_FENCE_FD_ANDROID 0x3145
#define EGL_SYNC_NATIVE_FENCE_SIGNALED_ANDROID 0x3146
#define EGL_SYNC_NEW_FRAME_NV 0x321F
#define EGL_SYNC_PRIOR_COMMANDS_COMPLETE 0x30F0
#define EGL_SYNC_PRIOR_COMMANDS_COMPLETE_KHR 0x30F0
#define EGL_SYNC_PRIOR_COMMANDS_COMPLETE_NV 0x30E6
#define EGL_SYNC_PRIOR_COMMANDS_IMPLICIT_EXTERNAL_ARM 0x328A
#define EGL_SYNC_REUSABLE_KHR 0x30FA
#define EGL_SYNC_STATUS 0x30F1
#define EGL_SYNC_STATUS_KHR 0x30F1
#define EGL_SYNC_STATUS_NV 0x30E7
#define EGL_SYNC_TYPE 0x30F7
#define EGL_SYNC_TYPE_KHR 0x30F7
#define EGL_SYNC_TYPE_NV 0x30ED
#define EGL_TELEMETRY_HINT_ANDROID 0x3570
#define EGL_TEXTURE_2D 0x305F
#define EGL_TEXTURE_EXTERNAL_WL 0x31DA
#define EGL_TEXTURE_FORMAT 0x3080
#define EGL_TEXTURE_RGB 0x305D
#define EGL_TEXTURE_RGBA 0x305E
#define EGL_TEXTURE_TARGET 0x3081
#define EGL_TEXTURE_Y_UV_WL 0x31D8
#define EGL_TEXTURE_Y_U_V_WL 0x31D7
#define EGL_TEXTURE_Y_XUXV_WL 0x31D9
#define EGL_TIMEOUT_EXPIRED 0x30F5
#define EGL_TIMEOUT_EXPIRED_KHR 0x30F5
#define EGL_TIMEOUT_EXPIRED_NV 0x30EB
#define EGL_TIMESTAMPS_ANDROID 0x3430
#define EGL_TIMESTAMP_INVALID_ANDROID EGL_CAST (EGLnsecsANDROID, -1)
#define EGL_TIMESTAMP_PENDING_ANDROID EGL_CAST (EGLnsecsANDROID, -2)
#define EGL_TOP_NV 0x336D
#define EGL_TRACK_REFERENCES_KHR 0x3352
#define EGL_TRANSPARENT_BLUE_VALUE 0x3035
#define EGL_TRANSPARENT_GREEN_VALUE 0x3036
#define EGL_TRANSPARENT_RED_VALUE 0x3037
#define EGL_TRANSPARENT_RGB 0x3052
#define EGL_TRANSPARENT_TYPE 0x3034
#define EGL_TRIPLE_BUFFER_NV 0x3230
#define EGL_TRUE 1
#define EGL_UNKNOWN EGL_CAST (EGLint, -1)
#define EGL_UNSIGNALED 0x30F3
#define EGL_UNSIGNALED_KHR 0x30F3
#define EGL_UNSIGNALED_NV 0x30E9
#define EGL_UPPER_LEFT_KHR 0x30CF
#define EGL_VENDOR 0x3053
#define EGL_VERSION 0x3054
#define EGL_VERTICAL_RESOLUTION 0x3091
#define EGL_VG_ALPHA_FORMAT 0x3088
#define EGL_VG_ALPHA_FORMAT_NONPRE 0x308B
#define EGL_VG_ALPHA_FORMAT_PRE 0x308C
#define EGL_VG_ALPHA_FORMAT_PRE_BIT 0x0040
#define EGL_VG_ALPHA_FORMAT_PRE_BIT_KHR 0x0040
#define EGL_VG_COLORSPACE 0x3087
#define EGL_VG_COLORSPACE_LINEAR 0x308A
#define EGL_VG_COLORSPACE_LINEAR_BIT 0x0020
#define EGL_VG_COLORSPACE_LINEAR_BIT_KHR 0x0020
#define EGL_VG_COLORSPACE_sRGB 0x3089
#define EGL_VG_PARENT_IMAGE_KHR 0x30BA
#define EGL_WAYLAND_BUFFER_WL 0x31D5
#define EGL_WAYLAND_PLANE_WL 0x31D6
#define EGL_WAYLAND_Y_INVERTED_WL 0x31DB
#define EGL_WIDTH 0x3057
#define EGL_WINDOW_BIT 0x0004
#define EGL_WRITE_SURFACE_BIT_KHR 0x0002
#define EGL_X_AXIS_NV 0x336F
#define EGL_YUV_BUFFER_EXT 0x3300
#define EGL_YUV_CHROMA_HORIZONTAL_SITING_HINT_EXT 0x327D
#define EGL_YUV_CHROMA_SITING_0_5_EXT 0x3285
#define EGL_YUV_CHROMA_SITING_0_EXT 0x3284
#define EGL_YUV_CHROMA_VERTICAL_SITING_HINT_EXT 0x327E
#define EGL_YUV_COLOR_SPACE_HINT_EXT 0x327B
#define EGL_YUV_CSC_STANDARD_2020_EXT 0x330D
#define EGL_YUV_CSC_STANDARD_601_EXT 0x330B
#define EGL_YUV_CSC_STANDARD_709_EXT 0x330C
#define EGL_YUV_CSC_STANDARD_EXT 0x330A
#define EGL_YUV_DEPTH_RANGE_EXT 0x3317
#define EGL_YUV_DEPTH_RANGE_FULL_EXT 0x3319
#define EGL_YUV_DEPTH_RANGE_LIMITED_EXT 0x3318
#define EGL_YUV_FULL_RANGE_EXT 0x3282
#define EGL_YUV_NARROW_RANGE_EXT 0x3283
#define EGL_YUV_NUMBER_OF_PLANES_EXT 0x3311
#define EGL_YUV_ORDER_AYUV_EXT 0x3308
#define EGL_YUV_ORDER_EXT 0x3301
#define EGL_YUV_ORDER_UYVY_EXT 0x3305
#define EGL_YUV_ORDER_VYUY_EXT 0x3307
#define EGL_YUV_ORDER_YUV_EXT 0x3302
#define EGL_YUV_ORDER_YUYV_EXT 0x3304
#define EGL_YUV_ORDER_YVU_EXT 0x3303
#define EGL_YUV_ORDER_YVYU_EXT 0x3306
#define EGL_YUV_PLANE0_TEXTURE_UNIT_NV 0x332C
#define EGL_YUV_PLANE1_TEXTURE_UNIT_NV 0x332D
#define EGL_YUV_PLANE2_TEXTURE_UNIT_NV 0x332E
#define EGL_YUV_PLANE_BPP_0_EXT 0x331B
#define EGL_YUV_PLANE_BPP_10_EXT 0x331D
#define EGL_YUV_PLANE_BPP_8_EXT 0x331C
#define EGL_YUV_PLANE_BPP_EXT 0x331A
#define EGL_YUV_SUBSAMPLE_4_2_0_EXT 0x3313
#define EGL_YUV_SUBSAMPLE_4_2_2_EXT 0x3314
#define EGL_YUV_SUBSAMPLE_4_4_4_EXT 0x3315
#define EGL_YUV_SUBSAMPLE_EXT 0x3312
#define EGL_Y_AXIS_NV 0x3370
#define EGL_Y_INVERTED_NOK 0x307F

#include <KHR/khrplatform.h>
#include <EGL/eglplatform.h>

struct AHardwareBuffer;
struct wl_buffer;
struct wl_display;
struct wl_resource;

typedef unsigned int EGLBoolean;
typedef unsigned int EGLenum;
typedef intptr_t EGLAttribKHR;
typedef intptr_t EGLAttrib;
typedef void* EGLClientBuffer;
typedef void* EGLConfig;
typedef void* EGLContext;
typedef void* EGLDeviceEXT;
typedef void* EGLDisplay;
typedef void* EGLImage;
typedef void* EGLImageKHR;
typedef void* EGLLabelKHR;
typedef void* EGLObjectKHR;
typedef void* EGLOutputLayerEXT;
typedef void* EGLOutputPortEXT;
typedef void* EGLStreamKHR;
typedef void* EGLSurface;
typedef void* EGLSync;
typedef void* EGLSyncKHR;
typedef void* EGLSyncNV;
typedef void (*__eglMustCastToProperFunctionPointerType) (void);
typedef khronos_utime_nanoseconds_t EGLTimeKHR;
typedef khronos_utime_nanoseconds_t EGLTime;
typedef khronos_utime_nanoseconds_t EGLTimeNV;
typedef khronos_utime_nanoseconds_t EGLuint64NV;
typedef khronos_uint64_t EGLuint64KHR;
typedef khronos_stime_nanoseconds_t EGLnsecsANDROID;
typedef int EGLNativeFileDescriptorKHR;
typedef khronos_ssize_t EGLsizeiANDROID;
typedef void (*EGLSetBlobFuncANDROID) (const void* key,
                                       EGLsizeiANDROID keySize,
                                       const void* value,
                                       EGLsizeiANDROID valueSize);
typedef EGLsizeiANDROID (*EGLGetBlobFuncANDROID) (const void* key,
                                                  EGLsizeiANDROID keySize,
                                                  void* value,
                                                  EGLsizeiANDROID valueSize);
struct EGLClientPixmapHI {
  void* pData;
  EGLint iWidth;
  EGLint iHeight;
  EGLint iStride;
};
typedef void (GLEXT_API_PTR* EGLDEBUGPROCKHR) (
  EGLenum error, const char* command, EGLint messageType,
  EGLLabelKHR threadLabel, EGLLabelKHR objectLabel, const char* message);
#define PFNEGLBINDWAYLANDDISPLAYWL PFNEGLBINDWAYLANDDISPLAYWLPROC
#define PFNEGLUNBINDWAYLANDDISPLAYWL PFNEGLUNBINDWAYLANDDISPLAYWLPROC
#define PFNEGLQUERYWAYLANDBUFFERWL PFNEGLQUERYWAYLANDBUFFERWLPROC
#define PFNEGLCREATEWAYLANDBUFFERFROMIMAGEWL                                  \
  PFNEGLCREATEWAYLANDBUFFERFROMIMAGEWLPROC

#define EGL_VERSION_1_0 1
GLEXT_API_CALL int GLEXT_EGL_VERSION_1_0;
#define EGL_VERSION_1_1 1
GLEXT_API_CALL int GLEXT_EGL_VERSION_1_1;
#define EGL_VERSION_1_2 1
GLEXT_API_CALL int GLEXT_EGL_VERSION_1_2;
#define EGL_VERSION_1_3 1
GLEXT_API_CALL int GLEXT_EGL_VERSION_1_3;
#define EGL_VERSION_1_4 1
GLEXT_API_CALL int GLEXT_EGL_VERSION_1_4;
#define EGL_VERSION_1_5 1
GLEXT_API_CALL int GLEXT_EGL_VERSION_1_5;
#define EGL_ANDROID_GLES_layers 1
GLEXT_API_CALL int GLEXT_EGL_ANDROID_GLES_layers;
#define EGL_ANDROID_blob_cache 1
GLEXT_API_CALL int GLEXT_EGL_ANDROID_blob_cache;
#define EGL_ANDROID_create_native_client_buffer 1
GLEXT_API_CALL int GLEXT_EGL_ANDROID_create_native_client_buffer;
#define EGL_ANDROID_framebuffer_target 1
GLEXT_API_CALL int GLEXT_EGL_ANDROID_framebuffer_target;
#define EGL_ANDROID_front_buffer_auto_refresh 1
GLEXT_API_CALL int GLEXT_EGL_ANDROID_front_buffer_auto_refresh;
#define EGL_ANDROID_get_frame_timestamps 1
GLEXT_API_CALL int GLEXT_EGL_ANDROID_get_frame_timestamps;
#define EGL_ANDROID_get_native_client_buffer 1
GLEXT_API_CALL int GLEXT_EGL_ANDROID_get_native_client_buffer;
#define EGL_ANDROID_image_native_buffer 1
GLEXT_API_CALL int GLEXT_EGL_ANDROID_image_native_buffer;
#define EGL_ANDROID_native_fence_sync 1
GLEXT_API_CALL int GLEXT_EGL_ANDROID_native_fence_sync;
#define EGL_ANDROID_presentation_time 1
GLEXT_API_CALL int GLEXT_EGL_ANDROID_presentation_time;
#define EGL_ANDROID_recordable 1
GLEXT_API_CALL int GLEXT_EGL_ANDROID_recordable;
#define EGL_ANDROID_telemetry_hint 1
GLEXT_API_CALL int GLEXT_EGL_ANDROID_telemetry_hint;
#define EGL_ANGLE_d3d_share_handle_client_buffer 1
GLEXT_API_CALL int GLEXT_EGL_ANGLE_d3d_share_handle_client_buffer;
#define EGL_ANGLE_device_d3d 1
GLEXT_API_CALL int GLEXT_EGL_ANGLE_device_d3d;
#define EGL_ANGLE_query_surface_pointer 1
GLEXT_API_CALL int GLEXT_EGL_ANGLE_query_surface_pointer;
#define EGL_ANGLE_surface_d3d_texture_2d_share_handle 1
GLEXT_API_CALL int GLEXT_EGL_ANGLE_surface_d3d_texture_2d_share_handle;
#define EGL_ANGLE_sync_control_rate 1
GLEXT_API_CALL int GLEXT_EGL_ANGLE_sync_control_rate;
#define EGL_ANGLE_window_fixed_size 1
GLEXT_API_CALL int GLEXT_EGL_ANGLE_window_fixed_size;
#define EGL_ARM_image_format 1
GLEXT_API_CALL int GLEXT_EGL_ARM_image_format;
#define EGL_ARM_implicit_external_sync 1
GLEXT_API_CALL int GLEXT_EGL_ARM_implicit_external_sync;
#define EGL_ARM_pixmap_multisample_discard 1
GLEXT_API_CALL int GLEXT_EGL_ARM_pixmap_multisample_discard;
#define EGL_EXT_bind_to_front 1
GLEXT_API_CALL int GLEXT_EGL_EXT_bind_to_front;
#define EGL_EXT_buffer_age 1
GLEXT_API_CALL int GLEXT_EGL_EXT_buffer_age;
#define EGL_EXT_client_extensions 1
GLEXT_API_CALL int GLEXT_EGL_EXT_client_extensions;
#define EGL_EXT_client_sync 1
GLEXT_API_CALL int GLEXT_EGL_EXT_client_sync;
#define EGL_EXT_compositor 1
GLEXT_API_CALL int GLEXT_EGL_EXT_compositor;
#define EGL_EXT_config_select_group 1
GLEXT_API_CALL int GLEXT_EGL_EXT_config_select_group;
#define EGL_EXT_create_context_robustness 1
GLEXT_API_CALL int GLEXT_EGL_EXT_create_context_robustness;
#define EGL_EXT_device_base 1
GLEXT_API_CALL int GLEXT_EGL_EXT_device_base;
#define EGL_EXT_device_drm 1
GLEXT_API_CALL int GLEXT_EGL_EXT_device_drm;
#define EGL_EXT_device_drm_render_node 1
GLEXT_API_CALL int GLEXT_EGL_EXT_device_drm_render_node;
#define EGL_EXT_device_enumeration 1
GLEXT_API_CALL int GLEXT_EGL_EXT_device_enumeration;
#define EGL_EXT_device_openwf 1
GLEXT_API_CALL int GLEXT_EGL_EXT_device_openwf;
#define EGL_EXT_device_persistent_id 1
GLEXT_API_CALL int GLEXT_EGL_EXT_device_persistent_id;
#define EGL_EXT_device_query 1
GLEXT_API_CALL int GLEXT_EGL_EXT_device_query;
#define EGL_EXT_device_query_name 1
GLEXT_API_CALL int GLEXT_EGL_EXT_device_query_name;
#define EGL_EXT_device_type 1
GLEXT_API_CALL int GLEXT_EGL_EXT_device_type;
#define EGL_EXT_display_alloc 1
GLEXT_API_CALL int GLEXT_EGL_EXT_display_alloc;
#define EGL_EXT_explicit_device 1
GLEXT_API_CALL int GLEXT_EGL_EXT_explicit_device;
#define EGL_EXT_gl_colorspace_bt2020_hlg 1
GLEXT_API_CALL int GLEXT_EGL_EXT_gl_colorspace_bt2020_hlg;
#define EGL_EXT_gl_colorspace_bt2020_linear 1
GLEXT_API_CALL int GLEXT_EGL_EXT_gl_colorspace_bt2020_linear;
#define EGL_EXT_gl_colorspace_bt2020_pq 1
GLEXT_API_CALL int GLEXT_EGL_EXT_gl_colorspace_bt2020_pq;
#define EGL_EXT_gl_colorspace_display_p3 1
GLEXT_API_CALL int GLEXT_EGL_EXT_gl_colorspace_display_p3;
#define EGL_EXT_gl_colorspace_display_p3_linear 1
GLEXT_API_CALL int GLEXT_EGL_EXT_gl_colorspace_display_p3_linear;
#define EGL_EXT_gl_colorspace_display_p3_passthrough 1
GLEXT_API_CALL int GLEXT_EGL_EXT_gl_colorspace_display_p3_passthrough;
#define EGL_EXT_gl_colorspace_scrgb 1
GLEXT_API_CALL int GLEXT_EGL_EXT_gl_colorspace_scrgb;
#define EGL_EXT_gl_colorspace_scrgb_linear 1
GLEXT_API_CALL int GLEXT_EGL_EXT_gl_colorspace_scrgb_linear;
#define EGL_EXT_image_dma_buf_import 1
GLEXT_API_CALL int GLEXT_EGL_EXT_image_dma_buf_import;
#define EGL_EXT_image_dma_buf_import_modifiers 1
GLEXT_API_CALL int GLEXT_EGL_EXT_image_dma_buf_import_modifiers;
#define EGL_EXT_image_gl_colorspace 1
GLEXT_API_CALL int GLEXT_EGL_EXT_image_gl_colorspace;
#define EGL_EXT_image_implicit_sync_control 1
GLEXT_API_CALL int GLEXT_EGL_EXT_image_implicit_sync_control;
#define EGL_EXT_multiview_window 1
GLEXT_API_CALL int GLEXT_EGL_EXT_multiview_window;
#define EGL_EXT_output_base 1
GLEXT_API_CALL int GLEXT_EGL_EXT_output_base;
#define EGL_EXT_output_drm 1
GLEXT_API_CALL int GLEXT_EGL_EXT_output_drm;
#define EGL_EXT_output_openwf 1
GLEXT_API_CALL int GLEXT_EGL_EXT_output_openwf;
#define EGL_EXT_pixel_format_float 1
GLEXT_API_CALL int GLEXT_EGL_EXT_pixel_format_float;
#define EGL_EXT_platform_base 1
GLEXT_API_CALL int GLEXT_EGL_EXT_platform_base;
#define EGL_EXT_platform_device 1
GLEXT_API_CALL int GLEXT_EGL_EXT_platform_device;
#define EGL_EXT_platform_wayland 1
GLEXT_API_CALL int GLEXT_EGL_EXT_platform_wayland;
#define EGL_EXT_platform_x11 1
GLEXT_API_CALL int GLEXT_EGL_EXT_platform_x11;
#define EGL_EXT_platform_xcb 1
GLEXT_API_CALL int GLEXT_EGL_EXT_platform_xcb;
#define EGL_EXT_present_opaque 1
GLEXT_API_CALL int GLEXT_EGL_EXT_present_opaque;
#define EGL_EXT_protected_content 1
GLEXT_API_CALL int GLEXT_EGL_EXT_protected_content;
#define EGL_EXT_protected_surface 1
GLEXT_API_CALL int GLEXT_EGL_EXT_protected_surface;
#define EGL_EXT_query_reset_notification_strategy 1
GLEXT_API_CALL int GLEXT_EGL_EXT_query_reset_notification_strategy;
#define EGL_EXT_stream_consumer_egloutput 1
GLEXT_API_CALL int GLEXT_EGL_EXT_stream_consumer_egloutput;
#define EGL_EXT_surface_CTA861_3_metadata 1
GLEXT_API_CALL int GLEXT_EGL_EXT_surface_CTA861_3_metadata;
#define EGL_EXT_surface_SMPTE2086_metadata 1
GLEXT_API_CALL int GLEXT_EGL_EXT_surface_SMPTE2086_metadata;
#define EGL_EXT_surface_compression 1
GLEXT_API_CALL int GLEXT_EGL_EXT_surface_compression;
#define EGL_EXT_swap_buffers_with_damage 1
GLEXT_API_CALL int GLEXT_EGL_EXT_swap_buffers_with_damage;
#define EGL_EXT_sync_reuse 1
GLEXT_API_CALL int GLEXT_EGL_EXT_sync_reuse;
#define EGL_EXT_yuv_surface 1
GLEXT_API_CALL int GLEXT_EGL_EXT_yuv_surface;
#define EGL_HI_clientpixmap 1
GLEXT_API_CALL int GLEXT_EGL_HI_clientpixmap;
#define EGL_HI_colorformats 1
GLEXT_API_CALL int GLEXT_EGL_HI_colorformats;
#define EGL_IMG_context_priority 1
GLEXT_API_CALL int GLEXT_EGL_IMG_context_priority;
#define EGL_IMG_image_plane_attribs 1
GLEXT_API_CALL int GLEXT_EGL_IMG_image_plane_attribs;
#define EGL_KHR_cl_event 1
GLEXT_API_CALL int GLEXT_EGL_KHR_cl_event;
#define EGL_KHR_cl_event2 1
GLEXT_API_CALL int GLEXT_EGL_KHR_cl_event2;
#define EGL_KHR_client_get_all_proc_addresses 1
GLEXT_API_CALL int GLEXT_EGL_KHR_client_get_all_proc_addresses;
#define EGL_KHR_config_attribs 1
GLEXT_API_CALL int GLEXT_EGL_KHR_config_attribs;
#define EGL_KHR_context_flush_control 1
GLEXT_API_CALL int GLEXT_EGL_KHR_context_flush_control;
#define EGL_KHR_create_context 1
GLEXT_API_CALL int GLEXT_EGL_KHR_create_context;
#define EGL_KHR_create_context_no_error 1
GLEXT_API_CALL int GLEXT_EGL_KHR_create_context_no_error;
#define EGL_KHR_debug 1
GLEXT_API_CALL int GLEXT_EGL_KHR_debug;
#define EGL_KHR_display_reference 1
GLEXT_API_CALL int GLEXT_EGL_KHR_display_reference;
#define EGL_KHR_fence_sync 1
GLEXT_API_CALL int GLEXT_EGL_KHR_fence_sync;
#define EGL_KHR_get_all_proc_addresses 1
GLEXT_API_CALL int GLEXT_EGL_KHR_get_all_proc_addresses;
#define EGL_KHR_gl_colorspace 1
GLEXT_API_CALL int GLEXT_EGL_KHR_gl_colorspace;
#define EGL_KHR_gl_renderbuffer_image 1
GLEXT_API_CALL int GLEXT_EGL_KHR_gl_renderbuffer_image;
#define EGL_KHR_gl_texture_2D_image 1
GLEXT_API_CALL int GLEXT_EGL_KHR_gl_texture_2D_image;
#define EGL_KHR_gl_texture_3D_image 1
GLEXT_API_CALL int GLEXT_EGL_KHR_gl_texture_3D_image;
#define EGL_KHR_gl_texture_cubemap_image 1
GLEXT_API_CALL int GLEXT_EGL_KHR_gl_texture_cubemap_image;
#define EGL_KHR_image 1
GLEXT_API_CALL int GLEXT_EGL_KHR_image;
#define EGL_KHR_image_base 1
GLEXT_API_CALL int GLEXT_EGL_KHR_image_base;
#define EGL_KHR_image_pixmap 1
GLEXT_API_CALL int GLEXT_EGL_KHR_image_pixmap;
#define EGL_KHR_lock_surface 1
GLEXT_API_CALL int GLEXT_EGL_KHR_lock_surface;
#define EGL_KHR_lock_surface2 1
GLEXT_API_CALL int GLEXT_EGL_KHR_lock_surface2;
#define EGL_KHR_lock_surface3 1
GLEXT_API_CALL int GLEXT_EGL_KHR_lock_surface3;
#define EGL_KHR_mutable_render_buffer 1
GLEXT_API_CALL int GLEXT_EGL_KHR_mutable_render_buffer;
#define EGL_KHR_no_config_context 1
GLEXT_API_CALL int GLEXT_EGL_KHR_no_config_context;
#define EGL_KHR_partial_update 1
GLEXT_API_CALL int GLEXT_EGL_KHR_partial_update;
#define EGL_KHR_platform_android 1
GLEXT_API_CALL int GLEXT_EGL_KHR_platform_android;
#define EGL_KHR_platform_gbm 1
GLEXT_API_CALL int GLEXT_EGL_KHR_platform_gbm;
#define EGL_KHR_platform_wayland 1
GLEXT_API_CALL int GLEXT_EGL_KHR_platform_wayland;
#define EGL_KHR_platform_x11 1
GLEXT_API_CALL int GLEXT_EGL_KHR_platform_x11;
#define EGL_KHR_reusable_sync 1
GLEXT_API_CALL int GLEXT_EGL_KHR_reusable_sync;
#define EGL_KHR_stream 1
GLEXT_API_CALL int GLEXT_EGL_KHR_stream;
#define EGL_KHR_stream_attrib 1
GLEXT_API_CALL int GLEXT_EGL_KHR_stream_attrib;
#define EGL_KHR_stream_consumer_gltexture 1
GLEXT_API_CALL int GLEXT_EGL_KHR_stream_consumer_gltexture;
#define EGL_KHR_stream_cross_process_fd 1
GLEXT_API_CALL int GLEXT_EGL_KHR_stream_cross_process_fd;
#define EGL_KHR_stream_fifo 1
GLEXT_API_CALL int GLEXT_EGL_KHR_stream_fifo;
#define EGL_KHR_stream_producer_aldatalocator 1
GLEXT_API_CALL int GLEXT_EGL_KHR_stream_producer_aldatalocator;
#define EGL_KHR_stream_producer_eglsurface 1
GLEXT_API_CALL int GLEXT_EGL_KHR_stream_producer_eglsurface;
#define EGL_KHR_surfaceless_context 1
GLEXT_API_CALL int GLEXT_EGL_KHR_surfaceless_context;
#define EGL_KHR_swap_buffers_with_damage 1
GLEXT_API_CALL int GLEXT_EGL_KHR_swap_buffers_with_damage;
#define EGL_KHR_vg_parent_image 1
GLEXT_API_CALL int GLEXT_EGL_KHR_vg_parent_image;
#define EGL_KHR_wait_sync 1
GLEXT_API_CALL int GLEXT_EGL_KHR_wait_sync;
#define EGL_MESA_drm_image 1
GLEXT_API_CALL int GLEXT_EGL_MESA_drm_image;
#define EGL_MESA_image_dma_buf_export 1
GLEXT_API_CALL int GLEXT_EGL_MESA_image_dma_buf_export;
#define EGL_MESA_platform_gbm 1
GLEXT_API_CALL int GLEXT_EGL_MESA_platform_gbm;
#define EGL_MESA_platform_surfaceless 1
GLEXT_API_CALL int GLEXT_EGL_MESA_platform_surfaceless;
#define EGL_MESA_query_driver 1
GLEXT_API_CALL int GLEXT_EGL_MESA_query_driver;
#define EGL_NOK_swap_region 1
GLEXT_API_CALL int GLEXT_EGL_NOK_swap_region;
#define EGL_NOK_swap_region2 1
GLEXT_API_CALL int GLEXT_EGL_NOK_swap_region2;
#define EGL_NOK_texture_from_pixmap 1
GLEXT_API_CALL int GLEXT_EGL_NOK_texture_from_pixmap;
#define EGL_NV_3dvision_surface 1
GLEXT_API_CALL int GLEXT_EGL_NV_3dvision_surface;
#define EGL_NV_context_priority_realtime 1
GLEXT_API_CALL int GLEXT_EGL_NV_context_priority_realtime;
#define EGL_NV_coverage_sample 1
GLEXT_API_CALL int GLEXT_EGL_NV_coverage_sample;
#define EGL_NV_coverage_sample_resolve 1
GLEXT_API_CALL int GLEXT_EGL_NV_coverage_sample_resolve;
#define EGL_NV_cuda_event 1
GLEXT_API_CALL int GLEXT_EGL_NV_cuda_event;
#define EGL_NV_depth_nonlinear 1
GLEXT_API_CALL int GLEXT_EGL_NV_depth_nonlinear;
#define EGL_NV_device_cuda 1
GLEXT_API_CALL int GLEXT_EGL_NV_device_cuda;
#define EGL_NV_native_query 1
GLEXT_API_CALL int GLEXT_EGL_NV_native_query;
#define EGL_NV_post_convert_rounding 1
GLEXT_API_CALL int GLEXT_EGL_NV_post_convert_rounding;
#define EGL_NV_post_sub_buffer 1
GLEXT_API_CALL int GLEXT_EGL_NV_post_sub_buffer;
#define EGL_NV_quadruple_buffer 1
GLEXT_API_CALL int GLEXT_EGL_NV_quadruple_buffer;
#define EGL_NV_robustness_video_memory_purge 1
GLEXT_API_CALL int GLEXT_EGL_NV_robustness_video_memory_purge;
#define EGL_NV_stream_consumer_eglimage 1
GLEXT_API_CALL int GLEXT_EGL_NV_stream_consumer_eglimage;
#define EGL_NV_stream_consumer_eglimage_use_scanout_attrib 1
GLEXT_API_CALL int GLEXT_EGL_NV_stream_consumer_eglimage_use_scanout_attrib;
#define EGL_NV_stream_consumer_gltexture_yuv 1
GLEXT_API_CALL int GLEXT_EGL_NV_stream_consumer_gltexture_yuv;
#define EGL_NV_stream_cross_display 1
GLEXT_API_CALL int GLEXT_EGL_NV_stream_cross_display;
#define EGL_NV_stream_cross_object 1
GLEXT_API_CALL int GLEXT_EGL_NV_stream_cross_object;
#define EGL_NV_stream_cross_partition 1
GLEXT_API_CALL int GLEXT_EGL_NV_stream_cross_partition;
#define EGL_NV_stream_cross_process 1
GLEXT_API_CALL int GLEXT_EGL_NV_stream_cross_process;
#define EGL_NV_stream_cross_system 1
GLEXT_API_CALL int GLEXT_EGL_NV_stream_cross_system;
#define EGL_NV_stream_dma 1
GLEXT_API_CALL int GLEXT_EGL_NV_stream_dma;
#define EGL_NV_stream_fifo_next 1
GLEXT_API_CALL int GLEXT_EGL_NV_stream_fifo_next;
#define EGL_NV_stream_fifo_synchronous 1
GLEXT_API_CALL int GLEXT_EGL_NV_stream_fifo_synchronous;
#define EGL_NV_stream_flush 1
GLEXT_API_CALL int GLEXT_EGL_NV_stream_flush;
#define EGL_NV_stream_frame_limits 1
GLEXT_API_CALL int GLEXT_EGL_NV_stream_frame_limits;
#define EGL_NV_stream_metadata 1
GLEXT_API_CALL int GLEXT_EGL_NV_stream_metadata;
#define EGL_NV_stream_origin 1
GLEXT_API_CALL int GLEXT_EGL_NV_stream_origin;
#define EGL_NV_stream_remote 1
GLEXT_API_CALL int GLEXT_EGL_NV_stream_remote;
#define EGL_NV_stream_reset 1
GLEXT_API_CALL int GLEXT_EGL_NV_stream_reset;
#define EGL_NV_stream_socket 1
GLEXT_API_CALL int GLEXT_EGL_NV_stream_socket;
#define EGL_NV_stream_socket_inet 1
GLEXT_API_CALL int GLEXT_EGL_NV_stream_socket_inet;
#define EGL_NV_stream_socket_unix 1
GLEXT_API_CALL int GLEXT_EGL_NV_stream_socket_unix;
#define EGL_NV_stream_sync 1
GLEXT_API_CALL int GLEXT_EGL_NV_stream_sync;
#define EGL_NV_sync 1
GLEXT_API_CALL int GLEXT_EGL_NV_sync;
#define EGL_NV_system_time 1
GLEXT_API_CALL int GLEXT_EGL_NV_system_time;
#define EGL_NV_triple_buffer 1
GLEXT_API_CALL int GLEXT_EGL_NV_triple_buffer;
#define EGL_QNX_image_native_buffer 1
GLEXT_API_CALL int GLEXT_EGL_QNX_image_native_buffer;
#define EGL_QNX_platform_screen 1
GLEXT_API_CALL int GLEXT_EGL_QNX_platform_screen;
#define EGL_TIZEN_image_native_buffer 1
GLEXT_API_CALL int GLEXT_EGL_TIZEN_image_native_buffer;
#define EGL_TIZEN_image_native_surface 1
GLEXT_API_CALL int GLEXT_EGL_TIZEN_image_native_surface;
#define EGL_WL_bind_wayland_display 1
GLEXT_API_CALL int GLEXT_EGL_WL_bind_wayland_display;
#define EGL_WL_create_wayland_buffer_from_image 1
GLEXT_API_CALL int GLEXT_EGL_WL_create_wayland_buffer_from_image;

typedef EGLBoolean (GLEXT_API_PTR* PFNEGLBINDAPIPROC) (EGLenum api);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLBINDTEXIMAGEPROC) (EGLDisplay dpy,
                                                            EGLSurface surface,
                                                            EGLint buffer);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLBINDWAYLANDDISPLAYWLPROC) (
  EGLDisplay dpy, struct wl_display* display);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLCHOOSECONFIGPROC) (
  EGLDisplay dpy, const EGLint* attrib_list, EGLConfig* configs,
  EGLint config_size, EGLint* num_config);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLCLIENTSIGNALSYNCEXTPROC) (
  EGLDisplay dpy, EGLSync sync, const EGLAttrib* attrib_list);
typedef EGLint (GLEXT_API_PTR* PFNEGLCLIENTWAITSYNCPROC) (EGLDisplay dpy,
                                                          EGLSync sync,
                                                          EGLint flags,
                                                          EGLTime timeout);
typedef EGLint (GLEXT_API_PTR* PFNEGLCLIENTWAITSYNCKHRPROC) (
  EGLDisplay dpy, EGLSyncKHR sync, EGLint flags, EGLTimeKHR timeout);
typedef EGLint (GLEXT_API_PTR* PFNEGLCLIENTWAITSYNCNVPROC) (EGLSyncNV sync,
                                                            EGLint flags,
                                                            EGLTimeNV timeout);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLCOMPOSITORBINDTEXWINDOWEXTPROC) (
  EGLint external_win_id);
typedef EGLBoolean (
  GLEXT_API_PTR* PFNEGLCOMPOSITORSETCONTEXTATTRIBUTESEXTPROC) (
  EGLint external_ref_id, const EGLint* context_attributes,
  EGLint num_entries);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLCOMPOSITORSETCONTEXTLISTEXTPROC) (
  const EGLint* external_ref_ids, EGLint num_entries);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLCOMPOSITORSETSIZEEXTPROC) (
  EGLint external_win_id, EGLint width, EGLint height);
typedef EGLBoolean (
  GLEXT_API_PTR* PFNEGLCOMPOSITORSETWINDOWATTRIBUTESEXTPROC) (
  EGLint external_win_id, const EGLint* window_attributes, EGLint num_entries);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLCOMPOSITORSETWINDOWLISTEXTPROC) (
  EGLint external_ref_id, const EGLint* external_win_ids, EGLint num_entries);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLCOMPOSITORSWAPPOLICYEXTPROC) (
  EGLint external_win_id, EGLint policy);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLCOPYBUFFERSPROC) (
  EGLDisplay dpy, EGLSurface surface, EGLNativePixmapType target);
typedef EGLContext (GLEXT_API_PTR* PFNEGLCREATECONTEXTPROC) (
  EGLDisplay dpy, EGLConfig config, EGLContext share_context,
  const EGLint* attrib_list);
typedef EGLImageKHR (GLEXT_API_PTR* PFNEGLCREATEDRMIMAGEMESAPROC) (
  EGLDisplay dpy, const EGLint* attrib_list);
typedef EGLSyncNV (GLEXT_API_PTR* PFNEGLCREATEFENCESYNCNVPROC) (
  EGLDisplay dpy, EGLenum condition, const EGLint* attrib_list);
typedef EGLImage (GLEXT_API_PTR* PFNEGLCREATEIMAGEPROC) (
  EGLDisplay dpy, EGLContext ctx, EGLenum target, EGLClientBuffer buffer,
  const EGLAttrib* attrib_list);
typedef EGLImageKHR (GLEXT_API_PTR* PFNEGLCREATEIMAGEKHRPROC) (
  EGLDisplay dpy, EGLContext ctx, EGLenum target, EGLClientBuffer buffer,
  const EGLint* attrib_list);
typedef EGLClientBuffer (
  GLEXT_API_PTR* PFNEGLCREATENATIVECLIENTBUFFERANDROIDPROC) (
  const EGLint* attrib_list);
typedef EGLSurface (GLEXT_API_PTR* PFNEGLCREATEPBUFFERFROMCLIENTBUFFERPROC) (
  EGLDisplay dpy, EGLenum buftype, EGLClientBuffer buffer, EGLConfig config,
  const EGLint* attrib_list);
typedef EGLSurface (GLEXT_API_PTR* PFNEGLCREATEPBUFFERSURFACEPROC) (
  EGLDisplay dpy, EGLConfig config, const EGLint* attrib_list);
typedef EGLSurface (GLEXT_API_PTR* PFNEGLCREATEPIXMAPSURFACEPROC) (
  EGLDisplay dpy, EGLConfig config, EGLNativePixmapType pixmap,
  const EGLint* attrib_list);
typedef EGLSurface (GLEXT_API_PTR* PFNEGLCREATEPIXMAPSURFACEHIPROC) (
  EGLDisplay dpy, EGLConfig config, struct EGLClientPixmapHI* pixmap);
typedef EGLSurface (GLEXT_API_PTR* PFNEGLCREATEPLATFORMPIXMAPSURFACEPROC) (
  EGLDisplay dpy, EGLConfig config, void* native_pixmap,
  const EGLAttrib* attrib_list);
typedef EGLSurface (GLEXT_API_PTR* PFNEGLCREATEPLATFORMPIXMAPSURFACEEXTPROC) (
  EGLDisplay dpy, EGLConfig config, void* native_pixmap,
  const EGLint* attrib_list);
typedef EGLSurface (GLEXT_API_PTR* PFNEGLCREATEPLATFORMWINDOWSURFACEPROC) (
  EGLDisplay dpy, EGLConfig config, void* native_window,
  const EGLAttrib* attrib_list);
typedef EGLSurface (GLEXT_API_PTR* PFNEGLCREATEPLATFORMWINDOWSURFACEEXTPROC) (
  EGLDisplay dpy, EGLConfig config, void* native_window,
  const EGLint* attrib_list);
typedef EGLStreamKHR (GLEXT_API_PTR* PFNEGLCREATESTREAMATTRIBKHRPROC) (
  EGLDisplay dpy, const EGLAttrib* attrib_list);
typedef EGLStreamKHR (
  GLEXT_API_PTR* PFNEGLCREATESTREAMFROMFILEDESCRIPTORKHRPROC) (
  EGLDisplay dpy, EGLNativeFileDescriptorKHR file_descriptor);
typedef EGLStreamKHR (GLEXT_API_PTR* PFNEGLCREATESTREAMKHRPROC) (
  EGLDisplay dpy, const EGLint* attrib_list);
typedef EGLSurface (GLEXT_API_PTR* PFNEGLCREATESTREAMPRODUCERSURFACEKHRPROC) (
  EGLDisplay dpy, EGLConfig config, EGLStreamKHR stream,
  const EGLint* attrib_list);
typedef EGLSyncKHR (GLEXT_API_PTR* PFNEGLCREATESTREAMSYNCNVPROC) (
  EGLDisplay dpy, EGLStreamKHR stream, EGLenum type,
  const EGLint* attrib_list);
typedef EGLSync (GLEXT_API_PTR* PFNEGLCREATESYNCPROC) (
  EGLDisplay dpy, EGLenum type, const EGLAttrib* attrib_list);
typedef EGLSyncKHR (GLEXT_API_PTR* PFNEGLCREATESYNC64KHRPROC) (
  EGLDisplay dpy, EGLenum type, const EGLAttribKHR* attrib_list);
typedef EGLSyncKHR (GLEXT_API_PTR* PFNEGLCREATESYNCKHRPROC) (
  EGLDisplay dpy, EGLenum type, const EGLint* attrib_list);
typedef struct wl_buffer*(
  GLEXT_API_PTR* PFNEGLCREATEWAYLANDBUFFERFROMIMAGEWLPROC) (EGLDisplay dpy,
                                                            EGLImageKHR image);
typedef EGLSurface (GLEXT_API_PTR* PFNEGLCREATEWINDOWSURFACEPROC) (
  EGLDisplay dpy, EGLConfig config, EGLNativeWindowType win,
  const EGLint* attrib_list);
typedef EGLint (GLEXT_API_PTR* PFNEGLDEBUGMESSAGECONTROLKHRPROC) (
  EGLDEBUGPROCKHR callback, const EGLAttrib* attrib_list);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLDESTROYCONTEXTPROC) (EGLDisplay dpy,
                                                              EGLContext ctx);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLDESTROYDISPLAYEXTPROC) (
  EGLDisplay dpy);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLDESTROYIMAGEPROC) (EGLDisplay dpy,
                                                            EGLImage image);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLDESTROYIMAGEKHRPROC) (
  EGLDisplay dpy, EGLImageKHR image);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLDESTROYSTREAMKHRPROC) (
  EGLDisplay dpy, EGLStreamKHR stream);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLDESTROYSURFACEPROC) (
  EGLDisplay dpy, EGLSurface surface);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLDESTROYSYNCPROC) (EGLDisplay dpy,
                                                           EGLSync sync);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLDESTROYSYNCKHRPROC) (EGLDisplay dpy,
                                                              EGLSyncKHR sync);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLDESTROYSYNCNVPROC) (EGLSyncNV sync);
typedef EGLint (GLEXT_API_PTR* PFNEGLDUPNATIVEFENCEFDANDROIDPROC) (
  EGLDisplay dpy, EGLSyncKHR sync);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLEXPORTDMABUFIMAGEMESAPROC) (
  EGLDisplay dpy, EGLImageKHR image, int* fds, EGLint* strides,
  EGLint* offsets);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLEXPORTDMABUFIMAGEQUERYMESAPROC) (
  EGLDisplay dpy, EGLImageKHR image, int* fourcc, int* num_planes,
  EGLuint64KHR* modifiers);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLEXPORTDRMIMAGEMESAPROC) (
  EGLDisplay dpy, EGLImageKHR image, EGLint* name, EGLint* handle,
  EGLint* stride);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLFENCENVPROC) (EGLSyncNV sync);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLGETCOMPOSITORTIMINGANDROIDPROC) (
  EGLDisplay dpy, EGLSurface surface, EGLint numTimestamps,
  const EGLint* names, EGLnsecsANDROID* values);
typedef EGLBoolean (
  GLEXT_API_PTR* PFNEGLGETCOMPOSITORTIMINGSUPPORTEDANDROIDPROC) (
  EGLDisplay dpy, EGLSurface surface, EGLint name);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLGETCONFIGATTRIBPROC) (
  EGLDisplay dpy, EGLConfig config, EGLint attribute, EGLint* value);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLGETCONFIGSPROC) (EGLDisplay dpy,
                                                          EGLConfig* configs,
                                                          EGLint config_size,
                                                          EGLint* num_config);
typedef EGLContext (GLEXT_API_PTR* PFNEGLGETCURRENTCONTEXTPROC) (void);
typedef EGLDisplay (GLEXT_API_PTR* PFNEGLGETCURRENTDISPLAYPROC) (void);
typedef EGLSurface (GLEXT_API_PTR* PFNEGLGETCURRENTSURFACEPROC) (
  EGLint readdraw);
typedef EGLDisplay (GLEXT_API_PTR* PFNEGLGETDISPLAYPROC) (
  EGLNativeDisplayType display_id);
typedef char*(GLEXT_API_PTR* PFNEGLGETDISPLAYDRIVERCONFIGPROC) (
  EGLDisplay dpy);
typedef const char*(GLEXT_API_PTR* PFNEGLGETDISPLAYDRIVERNAMEPROC) (
  EGLDisplay dpy);
typedef EGLint (GLEXT_API_PTR* PFNEGLGETERRORPROC) (void);
typedef EGLBoolean (
  GLEXT_API_PTR* PFNEGLGETFRAMETIMESTAMPSUPPORTEDANDROIDPROC) (
  EGLDisplay dpy, EGLSurface surface, EGLint timestamp);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLGETFRAMETIMESTAMPSANDROIDPROC) (
  EGLDisplay dpy, EGLSurface surface, EGLuint64KHR frameId,
  EGLint numTimestamps, const EGLint* timestamps, EGLnsecsANDROID* values);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLGETMSCRATEANGLEPROC) (
  EGLDisplay dpy, EGLSurface surface, EGLint* numerator, EGLint* denominator);
typedef EGLClientBuffer (
  GLEXT_API_PTR* PFNEGLGETNATIVECLIENTBUFFERANDROIDPROC) (
  const struct AHardwareBuffer* buffer);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLGETNEXTFRAMEIDANDROIDPROC) (
  EGLDisplay dpy, EGLSurface surface, EGLuint64KHR* frameId);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLGETOUTPUTLAYERSEXTPROC) (
  EGLDisplay dpy, const EGLAttrib* attrib_list, EGLOutputLayerEXT* layers,
  EGLint max_layers, EGLint* num_layers);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLGETOUTPUTPORTSEXTPROC) (
  EGLDisplay dpy, const EGLAttrib* attrib_list, EGLOutputPortEXT* ports,
  EGLint max_ports, EGLint* num_ports);
typedef EGLDisplay (GLEXT_API_PTR* PFNEGLGETPLATFORMDISPLAYPROC) (
  EGLenum platform, void* native_display, const EGLAttrib* attrib_list);
typedef EGLDisplay (GLEXT_API_PTR* PFNEGLGETPLATFORMDISPLAYEXTPROC) (
  EGLenum platform, void* native_display, const EGLint* attrib_list);
typedef __eglMustCastToProperFunctionPointerType (
  GLEXT_API_PTR* PFNEGLGETPROCADDRESSPROC) (const char* procname);
typedef EGLNativeFileDescriptorKHR (
  GLEXT_API_PTR* PFNEGLGETSTREAMFILEDESCRIPTORKHRPROC) (EGLDisplay dpy,
                                                        EGLStreamKHR stream);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLGETSYNCATTRIBPROC) (EGLDisplay dpy,
                                                             EGLSync sync,
                                                             EGLint attribute,
                                                             EGLAttrib* value);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLGETSYNCATTRIBKHRPROC) (
  EGLDisplay dpy, EGLSyncKHR sync, EGLint attribute, EGLint* value);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLGETSYNCATTRIBNVPROC) (
  EGLSyncNV sync, EGLint attribute, EGLint* value);
typedef EGLuint64NV (GLEXT_API_PTR* PFNEGLGETSYSTEMTIMEFREQUENCYNVPROC) (void);
typedef EGLuint64NV (GLEXT_API_PTR* PFNEGLGETSYSTEMTIMENVPROC) (void);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLINITIALIZEPROC) (EGLDisplay dpy,
                                                          EGLint* major,
                                                          EGLint* minor);
typedef EGLint (GLEXT_API_PTR* PFNEGLLABELOBJECTKHRPROC) (EGLDisplay display,
                                                          EGLenum objectType,
                                                          EGLObjectKHR object,
                                                          EGLLabelKHR label);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLLOCKSURFACEKHRPROC) (
  EGLDisplay dpy, EGLSurface surface, const EGLint* attrib_list);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLMAKECURRENTPROC) (EGLDisplay dpy,
                                                           EGLSurface draw,
                                                           EGLSurface read,
                                                           EGLContext ctx);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLOUTPUTLAYERATTRIBEXTPROC) (
  EGLDisplay dpy, EGLOutputLayerEXT layer, EGLint attribute, EGLAttrib value);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLOUTPUTPORTATTRIBEXTPROC) (
  EGLDisplay dpy, EGLOutputPortEXT port, EGLint attribute, EGLAttrib value);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLPOSTSUBBUFFERNVPROC) (
  EGLDisplay dpy, EGLSurface surface, EGLint x, EGLint y, EGLint width,
  EGLint height);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLPRESENTATIONTIMEANDROIDPROC) (
  EGLDisplay dpy, EGLSurface surface, EGLnsecsANDROID time);
typedef EGLenum (GLEXT_API_PTR* PFNEGLQUERYAPIPROC) (void);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYCONTEXTPROC) (EGLDisplay dpy,
                                                            EGLContext ctx,
                                                            EGLint attribute,
                                                            EGLint* value);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYDEBUGKHRPROC) (EGLint attribute,
                                                             EGLAttrib* value);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYDEVICEATTRIBEXTPROC) (
  EGLDeviceEXT device, EGLint attribute, EGLAttrib* value);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYDEVICEBINARYEXTPROC) (
  EGLDeviceEXT device, EGLint name, EGLint max_size, void* value,
  EGLint* size);
typedef const char*(GLEXT_API_PTR* PFNEGLQUERYDEVICESTRINGEXTPROC) (
  EGLDeviceEXT device, EGLint name);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYDEVICESEXTPROC) (
  EGLint max_devices, EGLDeviceEXT* devices, EGLint* num_devices);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYDISPLAYATTRIBEXTPROC) (
  EGLDisplay dpy, EGLint attribute, EGLAttrib* value);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYDISPLAYATTRIBKHRPROC) (
  EGLDisplay dpy, EGLint name, EGLAttrib* value);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYDISPLAYATTRIBNVPROC) (
  EGLDisplay dpy, EGLint attribute, EGLAttrib* value);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYDMABUFFORMATSEXTPROC) (
  EGLDisplay dpy, EGLint max_formats, EGLint* formats, EGLint* num_formats);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYDMABUFMODIFIERSEXTPROC) (
  EGLDisplay dpy, EGLint format, EGLint max_modifiers, EGLuint64KHR* modifiers,
  EGLBoolean* external_only, EGLint* num_modifiers);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYNATIVEDISPLAYNVPROC) (
  EGLDisplay dpy, EGLNativeDisplayType* display_id);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYNATIVEPIXMAPNVPROC) (
  EGLDisplay dpy, EGLSurface surf, EGLNativePixmapType* pixmap);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYNATIVEWINDOWNVPROC) (
  EGLDisplay dpy, EGLSurface surf, EGLNativeWindowType* window);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYOUTPUTLAYERATTRIBEXTPROC) (
  EGLDisplay dpy, EGLOutputLayerEXT layer, EGLint attribute, EGLAttrib* value);
typedef const char*(GLEXT_API_PTR* PFNEGLQUERYOUTPUTLAYERSTRINGEXTPROC) (
  EGLDisplay dpy, EGLOutputLayerEXT layer, EGLint name);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYOUTPUTPORTATTRIBEXTPROC) (
  EGLDisplay dpy, EGLOutputPortEXT port, EGLint attribute, EGLAttrib* value);
typedef const char*(GLEXT_API_PTR* PFNEGLQUERYOUTPUTPORTSTRINGEXTPROC) (
  EGLDisplay dpy, EGLOutputPortEXT port, EGLint name);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYSTREAMATTRIBKHRPROC) (
  EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLAttrib* value);
typedef EGLint (GLEXT_API_PTR* PFNEGLQUERYSTREAMCONSUMEREVENTNVPROC) (
  EGLDisplay dpy, EGLStreamKHR stream, EGLTime timeout, EGLenum* event,
  EGLAttrib* aux);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYSTREAMKHRPROC) (
  EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLint* value);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYSTREAMMETADATANVPROC) (
  EGLDisplay dpy, EGLStreamKHR stream, EGLenum name, EGLint n, EGLint offset,
  EGLint size, void* data);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYSTREAMTIMEKHRPROC) (
  EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLTimeKHR* value);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYSTREAMU64KHRPROC) (
  EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLuint64KHR* value);
typedef const char*(GLEXT_API_PTR* PFNEGLQUERYSTRINGPROC) (EGLDisplay dpy,
                                                           EGLint name);
typedef EGLBoolean (
  GLEXT_API_PTR* PFNEGLQUERYSUPPORTEDCOMPRESSIONRATESEXTPROC) (
  EGLDisplay dpy, EGLConfig config, const EGLAttrib* attrib_list,
  EGLint* rates, EGLint rate_size, EGLint* num_rates);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYSURFACEPROC) (EGLDisplay dpy,
                                                            EGLSurface surface,
                                                            EGLint attribute,
                                                            EGLint* value);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYSURFACE64KHRPROC) (
  EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLAttribKHR* value);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYSURFACEPOINTERANGLEPROC) (
  EGLDisplay dpy, EGLSurface surface, EGLint attribute, void** value);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLQUERYWAYLANDBUFFERWLPROC) (
  EGLDisplay dpy, struct wl_resource* buffer, EGLint attribute, EGLint* value);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLRELEASETEXIMAGEPROC) (
  EGLDisplay dpy, EGLSurface surface, EGLint buffer);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLRELEASETHREADPROC) (void);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLRESETSTREAMNVPROC) (
  EGLDisplay dpy, EGLStreamKHR stream);
typedef void (GLEXT_API_PTR* PFNEGLSETBLOBCACHEFUNCSANDROIDPROC) (
  EGLDisplay dpy, EGLSetBlobFuncANDROID set, EGLGetBlobFuncANDROID get);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLSETDAMAGEREGIONKHRPROC) (
  EGLDisplay dpy, EGLSurface surface, EGLint* rects, EGLint n_rects);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLSETSTREAMATTRIBKHRPROC) (
  EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLAttrib value);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLSETSTREAMMETADATANVPROC) (
  EGLDisplay dpy, EGLStreamKHR stream, EGLint n, EGLint offset, EGLint size,
  const void* data);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLSIGNALSYNCKHRPROC) (EGLDisplay dpy,
                                                             EGLSyncKHR sync,
                                                             EGLenum mode);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLSIGNALSYNCNVPROC) (EGLSyncNV sync,
                                                            EGLenum mode);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLSTREAMACQUIREIMAGENVPROC) (
  EGLDisplay dpy, EGLStreamKHR stream, EGLImage* pImage, EGLSync sync);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLSTREAMATTRIBKHRPROC) (
  EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLint value);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLSTREAMCONSUMERACQUIREATTRIBKHRPROC) (
  EGLDisplay dpy, EGLStreamKHR stream, const EGLAttrib* attrib_list);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLSTREAMCONSUMERACQUIREKHRPROC) (
  EGLDisplay dpy, EGLStreamKHR stream);
typedef EGLBoolean (
  GLEXT_API_PTR* PFNEGLSTREAMCONSUMERGLTEXTUREEXTERNALATTRIBSNVPROC) (
  EGLDisplay dpy, EGLStreamKHR stream, const EGLAttrib* attrib_list);
typedef EGLBoolean (
  GLEXT_API_PTR* PFNEGLSTREAMCONSUMERGLTEXTUREEXTERNALKHRPROC) (
  EGLDisplay dpy, EGLStreamKHR stream);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLSTREAMCONSUMEROUTPUTEXTPROC) (
  EGLDisplay dpy, EGLStreamKHR stream, EGLOutputLayerEXT layer);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLSTREAMCONSUMERRELEASEATTRIBKHRPROC) (
  EGLDisplay dpy, EGLStreamKHR stream, const EGLAttrib* attrib_list);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLSTREAMCONSUMERRELEASEKHRPROC) (
  EGLDisplay dpy, EGLStreamKHR stream);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLSTREAMFLUSHNVPROC) (
  EGLDisplay dpy, EGLStreamKHR stream);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLSTREAMIMAGECONSUMERCONNECTNVPROC) (
  EGLDisplay dpy, EGLStreamKHR stream, EGLint num_modifiers,
  const EGLuint64KHR* modifiers, const EGLAttrib* attrib_list);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLSTREAMRELEASEIMAGENVPROC) (
  EGLDisplay dpy, EGLStreamKHR stream, EGLImage image, EGLSync sync);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLSURFACEATTRIBPROC) (
  EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLint value);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLSWAPBUFFERSPROC) (EGLDisplay dpy,
                                                           EGLSurface surface);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLSWAPBUFFERSREGION2NOKPROC) (
  EGLDisplay dpy, EGLSurface surface, EGLint numRects, const EGLint* rects);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLSWAPBUFFERSREGIONNOKPROC) (
  EGLDisplay dpy, EGLSurface surface, EGLint numRects, const EGLint* rects);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLSWAPBUFFERSWITHDAMAGEEXTPROC) (
  EGLDisplay dpy, EGLSurface surface, const EGLint* rects, EGLint n_rects);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLSWAPBUFFERSWITHDAMAGEKHRPROC) (
  EGLDisplay dpy, EGLSurface surface, const EGLint* rects, EGLint n_rects);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLSWAPINTERVALPROC) (EGLDisplay dpy,
                                                            EGLint interval);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLTERMINATEPROC) (EGLDisplay dpy);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLUNBINDWAYLANDDISPLAYWLPROC) (
  EGLDisplay dpy, struct wl_display* display);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLUNLOCKSURFACEKHRPROC) (
  EGLDisplay dpy, EGLSurface surface);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLUNSIGNALSYNCEXTPROC) (
  EGLDisplay dpy, EGLSync sync, const EGLAttrib* attrib_list);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLWAITCLIENTPROC) (void);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLWAITGLPROC) (void);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLWAITNATIVEPROC) (EGLint engine);
typedef EGLBoolean (GLEXT_API_PTR* PFNEGLWAITSYNCPROC) (EGLDisplay dpy,
                                                        EGLSync sync,
                                                        EGLint flags);
typedef EGLint (GLEXT_API_PTR* PFNEGLWAITSYNCKHRPROC) (EGLDisplay dpy,
                                                       EGLSyncKHR sync,
                                                       EGLint flags);

GLEXT_API_CALL PFNEGLBINDAPIPROC glext_eglBindAPI;
#define eglBindAPI glext_eglBindAPI
GLEXT_API_CALL PFNEGLBINDTEXIMAGEPROC glext_eglBindTexImage;
#define eglBindTexImage glext_eglBindTexImage
GLEXT_API_CALL PFNEGLBINDWAYLANDDISPLAYWLPROC glext_eglBindWaylandDisplayWL;
#define eglBindWaylandDisplayWL glext_eglBindWaylandDisplayWL
GLEXT_API_CALL PFNEGLCHOOSECONFIGPROC glext_eglChooseConfig;
#define eglChooseConfig glext_eglChooseConfig
GLEXT_API_CALL PFNEGLCLIENTSIGNALSYNCEXTPROC glext_eglClientSignalSyncEXT;
#define eglClientSignalSyncEXT glext_eglClientSignalSyncEXT
GLEXT_API_CALL PFNEGLCLIENTWAITSYNCPROC glext_eglClientWaitSync;
#define eglClientWaitSync glext_eglClientWaitSync
GLEXT_API_CALL PFNEGLCLIENTWAITSYNCKHRPROC glext_eglClientWaitSyncKHR;
#define eglClientWaitSyncKHR glext_eglClientWaitSyncKHR
GLEXT_API_CALL PFNEGLCLIENTWAITSYNCNVPROC glext_eglClientWaitSyncNV;
#define eglClientWaitSyncNV glext_eglClientWaitSyncNV
GLEXT_API_CALL PFNEGLCOMPOSITORBINDTEXWINDOWEXTPROC
  glext_eglCompositorBindTexWindowEXT;
#define eglCompositorBindTexWindowEXT glext_eglCompositorBindTexWindowEXT
GLEXT_API_CALL PFNEGLCOMPOSITORSETCONTEXTATTRIBUTESEXTPROC
  glext_eglCompositorSetContextAttributesEXT;
#define eglCompositorSetContextAttributesEXT                                  \
  glext_eglCompositorSetContextAttributesEXT
GLEXT_API_CALL PFNEGLCOMPOSITORSETCONTEXTLISTEXTPROC
  glext_eglCompositorSetContextListEXT;
#define eglCompositorSetContextListEXT glext_eglCompositorSetContextListEXT
GLEXT_API_CALL PFNEGLCOMPOSITORSETSIZEEXTPROC glext_eglCompositorSetSizeEXT;
#define eglCompositorSetSizeEXT glext_eglCompositorSetSizeEXT
GLEXT_API_CALL PFNEGLCOMPOSITORSETWINDOWATTRIBUTESEXTPROC
  glext_eglCompositorSetWindowAttributesEXT;
#define eglCompositorSetWindowAttributesEXT                                   \
  glext_eglCompositorSetWindowAttributesEXT
GLEXT_API_CALL PFNEGLCOMPOSITORSETWINDOWLISTEXTPROC
  glext_eglCompositorSetWindowListEXT;
#define eglCompositorSetWindowListEXT glext_eglCompositorSetWindowListEXT
GLEXT_API_CALL PFNEGLCOMPOSITORSWAPPOLICYEXTPROC
  glext_eglCompositorSwapPolicyEXT;
#define eglCompositorSwapPolicyEXT glext_eglCompositorSwapPolicyEXT
GLEXT_API_CALL PFNEGLCOPYBUFFERSPROC glext_eglCopyBuffers;
#define eglCopyBuffers glext_eglCopyBuffers
GLEXT_API_CALL PFNEGLCREATECONTEXTPROC glext_eglCreateContext;
#define eglCreateContext glext_eglCreateContext
GLEXT_API_CALL PFNEGLCREATEDRMIMAGEMESAPROC glext_eglCreateDRMImageMESA;
#define eglCreateDRMImageMESA glext_eglCreateDRMImageMESA
GLEXT_API_CALL PFNEGLCREATEFENCESYNCNVPROC glext_eglCreateFenceSyncNV;
#define eglCreateFenceSyncNV glext_eglCreateFenceSyncNV
GLEXT_API_CALL PFNEGLCREATEIMAGEPROC glext_eglCreateImage;
#define eglCreateImage glext_eglCreateImage
GLEXT_API_CALL PFNEGLCREATEIMAGEKHRPROC glext_eglCreateImageKHR;
#define eglCreateImageKHR glext_eglCreateImageKHR
GLEXT_API_CALL PFNEGLCREATENATIVECLIENTBUFFERANDROIDPROC
  glext_eglCreateNativeClientBufferANDROID;
#define eglCreateNativeClientBufferANDROID                                    \
  glext_eglCreateNativeClientBufferANDROID
GLEXT_API_CALL PFNEGLCREATEPBUFFERFROMCLIENTBUFFERPROC
  glext_eglCreatePbufferFromClientBuffer;
#define eglCreatePbufferFromClientBuffer glext_eglCreatePbufferFromClientBuffer
GLEXT_API_CALL PFNEGLCREATEPBUFFERSURFACEPROC glext_eglCreatePbufferSurface;
#define eglCreatePbufferSurface glext_eglCreatePbufferSurface
GLEXT_API_CALL PFNEGLCREATEPIXMAPSURFACEPROC glext_eglCreatePixmapSurface;
#define eglCreatePixmapSurface glext_eglCreatePixmapSurface
GLEXT_API_CALL PFNEGLCREATEPIXMAPSURFACEHIPROC glext_eglCreatePixmapSurfaceHI;
#define eglCreatePixmapSurfaceHI glext_eglCreatePixmapSurfaceHI
GLEXT_API_CALL PFNEGLCREATEPLATFORMPIXMAPSURFACEPROC
  glext_eglCreatePlatformPixmapSurface;
#define eglCreatePlatformPixmapSurface glext_eglCreatePlatformPixmapSurface
GLEXT_API_CALL PFNEGLCREATEPLATFORMPIXMAPSURFACEEXTPROC
  glext_eglCreatePlatformPixmapSurfaceEXT;
#define eglCreatePlatformPixmapSurfaceEXT                                     \
  glext_eglCreatePlatformPixmapSurfaceEXT
GLEXT_API_CALL PFNEGLCREATEPLATFORMWINDOWSURFACEPROC
  glext_eglCreatePlatformWindowSurface;
#define eglCreatePlatformWindowSurface glext_eglCreatePlatformWindowSurface
GLEXT_API_CALL PFNEGLCREATEPLATFORMWINDOWSURFACEEXTPROC
  glext_eglCreatePlatformWindowSurfaceEXT;
#define eglCreatePlatformWindowSurfaceEXT                                     \
  glext_eglCreatePlatformWindowSurfaceEXT
GLEXT_API_CALL PFNEGLCREATESTREAMATTRIBKHRPROC glext_eglCreateStreamAttribKHR;
#define eglCreateStreamAttribKHR glext_eglCreateStreamAttribKHR
GLEXT_API_CALL PFNEGLCREATESTREAMFROMFILEDESCRIPTORKHRPROC
  glext_eglCreateStreamFromFileDescriptorKHR;
#define eglCreateStreamFromFileDescriptorKHR                                  \
  glext_eglCreateStreamFromFileDescriptorKHR
GLEXT_API_CALL PFNEGLCREATESTREAMKHRPROC glext_eglCreateStreamKHR;
#define eglCreateStreamKHR glext_eglCreateStreamKHR
GLEXT_API_CALL PFNEGLCREATESTREAMPRODUCERSURFACEKHRPROC
  glext_eglCreateStreamProducerSurfaceKHR;
#define eglCreateStreamProducerSurfaceKHR                                     \
  glext_eglCreateStreamProducerSurfaceKHR
GLEXT_API_CALL PFNEGLCREATESTREAMSYNCNVPROC glext_eglCreateStreamSyncNV;
#define eglCreateStreamSyncNV glext_eglCreateStreamSyncNV
GLEXT_API_CALL PFNEGLCREATESYNCPROC glext_eglCreateSync;
#define eglCreateSync glext_eglCreateSync
GLEXT_API_CALL PFNEGLCREATESYNC64KHRPROC glext_eglCreateSync64KHR;
#define eglCreateSync64KHR glext_eglCreateSync64KHR
GLEXT_API_CALL PFNEGLCREATESYNCKHRPROC glext_eglCreateSyncKHR;
#define eglCreateSyncKHR glext_eglCreateSyncKHR
GLEXT_API_CALL PFNEGLCREATEWAYLANDBUFFERFROMIMAGEWLPROC
  glext_eglCreateWaylandBufferFromImageWL;
#define eglCreateWaylandBufferFromImageWL                                     \
  glext_eglCreateWaylandBufferFromImageWL
GLEXT_API_CALL PFNEGLCREATEWINDOWSURFACEPROC glext_eglCreateWindowSurface;
#define eglCreateWindowSurface glext_eglCreateWindowSurface
GLEXT_API_CALL PFNEGLDEBUGMESSAGECONTROLKHRPROC
  glext_eglDebugMessageControlKHR;
#define eglDebugMessageControlKHR glext_eglDebugMessageControlKHR
GLEXT_API_CALL PFNEGLDESTROYCONTEXTPROC glext_eglDestroyContext;
#define eglDestroyContext glext_eglDestroyContext
GLEXT_API_CALL PFNEGLDESTROYDISPLAYEXTPROC glext_eglDestroyDisplayEXT;
#define eglDestroyDisplayEXT glext_eglDestroyDisplayEXT
GLEXT_API_CALL PFNEGLDESTROYIMAGEPROC glext_eglDestroyImage;
#define eglDestroyImage glext_eglDestroyImage
GLEXT_API_CALL PFNEGLDESTROYIMAGEKHRPROC glext_eglDestroyImageKHR;
#define eglDestroyImageKHR glext_eglDestroyImageKHR
GLEXT_API_CALL PFNEGLDESTROYSTREAMKHRPROC glext_eglDestroyStreamKHR;
#define eglDestroyStreamKHR glext_eglDestroyStreamKHR
GLEXT_API_CALL PFNEGLDESTROYSURFACEPROC glext_eglDestroySurface;
#define eglDestroySurface glext_eglDestroySurface
GLEXT_API_CALL PFNEGLDESTROYSYNCPROC glext_eglDestroySync;
#define eglDestroySync glext_eglDestroySync
GLEXT_API_CALL PFNEGLDESTROYSYNCKHRPROC glext_eglDestroySyncKHR;
#define eglDestroySyncKHR glext_eglDestroySyncKHR
GLEXT_API_CALL PFNEGLDESTROYSYNCNVPROC glext_eglDestroySyncNV;
#define eglDestroySyncNV glext_eglDestroySyncNV
GLEXT_API_CALL PFNEGLDUPNATIVEFENCEFDANDROIDPROC
  glext_eglDupNativeFenceFDANDROID;
#define eglDupNativeFenceFDANDROID glext_eglDupNativeFenceFDANDROID
GLEXT_API_CALL PFNEGLEXPORTDMABUFIMAGEMESAPROC glext_eglExportDMABUFImageMESA;
#define eglExportDMABUFImageMESA glext_eglExportDMABUFImageMESA
GLEXT_API_CALL PFNEGLEXPORTDMABUFIMAGEQUERYMESAPROC
  glext_eglExportDMABUFImageQueryMESA;
#define eglExportDMABUFImageQueryMESA glext_eglExportDMABUFImageQueryMESA
GLEXT_API_CALL PFNEGLEXPORTDRMIMAGEMESAPROC glext_eglExportDRMImageMESA;
#define eglExportDRMImageMESA glext_eglExportDRMImageMESA
GLEXT_API_CALL PFNEGLFENCENVPROC glext_eglFenceNV;
#define eglFenceNV glext_eglFenceNV
GLEXT_API_CALL PFNEGLGETCOMPOSITORTIMINGANDROIDPROC
  glext_eglGetCompositorTimingANDROID;
#define eglGetCompositorTimingANDROID glext_eglGetCompositorTimingANDROID
GLEXT_API_CALL PFNEGLGETCOMPOSITORTIMINGSUPPORTEDANDROIDPROC
  glext_eglGetCompositorTimingSupportedANDROID;
#define eglGetCompositorTimingSupportedANDROID                                \
  glext_eglGetCompositorTimingSupportedANDROID
GLEXT_API_CALL PFNEGLGETCONFIGATTRIBPROC glext_eglGetConfigAttrib;
#define eglGetConfigAttrib glext_eglGetConfigAttrib
GLEXT_API_CALL PFNEGLGETCONFIGSPROC glext_eglGetConfigs;
#define eglGetConfigs glext_eglGetConfigs
GLEXT_API_CALL PFNEGLGETCURRENTCONTEXTPROC glext_eglGetCurrentContext;
#define eglGetCurrentContext glext_eglGetCurrentContext
GLEXT_API_CALL PFNEGLGETCURRENTDISPLAYPROC glext_eglGetCurrentDisplay;
#define eglGetCurrentDisplay glext_eglGetCurrentDisplay
GLEXT_API_CALL PFNEGLGETCURRENTSURFACEPROC glext_eglGetCurrentSurface;
#define eglGetCurrentSurface glext_eglGetCurrentSurface
GLEXT_API_CALL PFNEGLGETDISPLAYPROC glext_eglGetDisplay;
#define eglGetDisplay glext_eglGetDisplay
GLEXT_API_CALL PFNEGLGETDISPLAYDRIVERCONFIGPROC
  glext_eglGetDisplayDriverConfig;
#define eglGetDisplayDriverConfig glext_eglGetDisplayDriverConfig
GLEXT_API_CALL PFNEGLGETDISPLAYDRIVERNAMEPROC glext_eglGetDisplayDriverName;
#define eglGetDisplayDriverName glext_eglGetDisplayDriverName
GLEXT_API_CALL PFNEGLGETERRORPROC glext_eglGetError;
#define eglGetError glext_eglGetError
GLEXT_API_CALL PFNEGLGETFRAMETIMESTAMPSUPPORTEDANDROIDPROC
  glext_eglGetFrameTimestampSupportedANDROID;
#define eglGetFrameTimestampSupportedANDROID                                  \
  glext_eglGetFrameTimestampSupportedANDROID
GLEXT_API_CALL PFNEGLGETFRAMETIMESTAMPSANDROIDPROC
  glext_eglGetFrameTimestampsANDROID;
#define eglGetFrameTimestampsANDROID glext_eglGetFrameTimestampsANDROID
GLEXT_API_CALL PFNEGLGETMSCRATEANGLEPROC glext_eglGetMscRateANGLE;
#define eglGetMscRateANGLE glext_eglGetMscRateANGLE
GLEXT_API_CALL PFNEGLGETNATIVECLIENTBUFFERANDROIDPROC
  glext_eglGetNativeClientBufferANDROID;
#define eglGetNativeClientBufferANDROID glext_eglGetNativeClientBufferANDROID
GLEXT_API_CALL PFNEGLGETNEXTFRAMEIDANDROIDPROC glext_eglGetNextFrameIdANDROID;
#define eglGetNextFrameIdANDROID glext_eglGetNextFrameIdANDROID
GLEXT_API_CALL PFNEGLGETOUTPUTLAYERSEXTPROC glext_eglGetOutputLayersEXT;
#define eglGetOutputLayersEXT glext_eglGetOutputLayersEXT
GLEXT_API_CALL PFNEGLGETOUTPUTPORTSEXTPROC glext_eglGetOutputPortsEXT;
#define eglGetOutputPortsEXT glext_eglGetOutputPortsEXT
GLEXT_API_CALL PFNEGLGETPLATFORMDISPLAYPROC glext_eglGetPlatformDisplay;
#define eglGetPlatformDisplay glext_eglGetPlatformDisplay
GLEXT_API_CALL PFNEGLGETPLATFORMDISPLAYEXTPROC glext_eglGetPlatformDisplayEXT;
#define eglGetPlatformDisplayEXT glext_eglGetPlatformDisplayEXT
GLEXT_API_CALL PFNEGLGETPROCADDRESSPROC glext_eglGetProcAddress;
#define eglGetProcAddress glext_eglGetProcAddress
GLEXT_API_CALL PFNEGLGETSTREAMFILEDESCRIPTORKHRPROC
  glext_eglGetStreamFileDescriptorKHR;
#define eglGetStreamFileDescriptorKHR glext_eglGetStreamFileDescriptorKHR
GLEXT_API_CALL PFNEGLGETSYNCATTRIBPROC glext_eglGetSyncAttrib;
#define eglGetSyncAttrib glext_eglGetSyncAttrib
GLEXT_API_CALL PFNEGLGETSYNCATTRIBKHRPROC glext_eglGetSyncAttribKHR;
#define eglGetSyncAttribKHR glext_eglGetSyncAttribKHR
GLEXT_API_CALL PFNEGLGETSYNCATTRIBNVPROC glext_eglGetSyncAttribNV;
#define eglGetSyncAttribNV glext_eglGetSyncAttribNV
GLEXT_API_CALL PFNEGLGETSYSTEMTIMEFREQUENCYNVPROC
  glext_eglGetSystemTimeFrequencyNV;
#define eglGetSystemTimeFrequencyNV glext_eglGetSystemTimeFrequencyNV
GLEXT_API_CALL PFNEGLGETSYSTEMTIMENVPROC glext_eglGetSystemTimeNV;
#define eglGetSystemTimeNV glext_eglGetSystemTimeNV
GLEXT_API_CALL PFNEGLINITIALIZEPROC glext_eglInitialize;
#define eglInitialize glext_eglInitialize
GLEXT_API_CALL PFNEGLLABELOBJECTKHRPROC glext_eglLabelObjectKHR;
#define eglLabelObjectKHR glext_eglLabelObjectKHR
GLEXT_API_CALL PFNEGLLOCKSURFACEKHRPROC glext_eglLockSurfaceKHR;
#define eglLockSurfaceKHR glext_eglLockSurfaceKHR
GLEXT_API_CALL PFNEGLMAKECURRENTPROC glext_eglMakeCurrent;
#define eglMakeCurrent glext_eglMakeCurrent
GLEXT_API_CALL PFNEGLOUTPUTLAYERATTRIBEXTPROC glext_eglOutputLayerAttribEXT;
#define eglOutputLayerAttribEXT glext_eglOutputLayerAttribEXT
GLEXT_API_CALL PFNEGLOUTPUTPORTATTRIBEXTPROC glext_eglOutputPortAttribEXT;
#define eglOutputPortAttribEXT glext_eglOutputPortAttribEXT
GLEXT_API_CALL PFNEGLPOSTSUBBUFFERNVPROC glext_eglPostSubBufferNV;
#define eglPostSubBufferNV glext_eglPostSubBufferNV
GLEXT_API_CALL PFNEGLPRESENTATIONTIMEANDROIDPROC
  glext_eglPresentationTimeANDROID;
#define eglPresentationTimeANDROID glext_eglPresentationTimeANDROID
GLEXT_API_CALL PFNEGLQUERYAPIPROC glext_eglQueryAPI;
#define eglQueryAPI glext_eglQueryAPI
GLEXT_API_CALL PFNEGLQUERYCONTEXTPROC glext_eglQueryContext;
#define eglQueryContext glext_eglQueryContext
GLEXT_API_CALL PFNEGLQUERYDEBUGKHRPROC glext_eglQueryDebugKHR;
#define eglQueryDebugKHR glext_eglQueryDebugKHR
GLEXT_API_CALL PFNEGLQUERYDEVICEATTRIBEXTPROC glext_eglQueryDeviceAttribEXT;
#define eglQueryDeviceAttribEXT glext_eglQueryDeviceAttribEXT
GLEXT_API_CALL PFNEGLQUERYDEVICEBINARYEXTPROC glext_eglQueryDeviceBinaryEXT;
#define eglQueryDeviceBinaryEXT glext_eglQueryDeviceBinaryEXT
GLEXT_API_CALL PFNEGLQUERYDEVICESTRINGEXTPROC glext_eglQueryDeviceStringEXT;
#define eglQueryDeviceStringEXT glext_eglQueryDeviceStringEXT
GLEXT_API_CALL PFNEGLQUERYDEVICESEXTPROC glext_eglQueryDevicesEXT;
#define eglQueryDevicesEXT glext_eglQueryDevicesEXT
GLEXT_API_CALL PFNEGLQUERYDISPLAYATTRIBEXTPROC glext_eglQueryDisplayAttribEXT;
#define eglQueryDisplayAttribEXT glext_eglQueryDisplayAttribEXT
GLEXT_API_CALL PFNEGLQUERYDISPLAYATTRIBKHRPROC glext_eglQueryDisplayAttribKHR;
#define eglQueryDisplayAttribKHR glext_eglQueryDisplayAttribKHR
GLEXT_API_CALL PFNEGLQUERYDISPLAYATTRIBNVPROC glext_eglQueryDisplayAttribNV;
#define eglQueryDisplayAttribNV glext_eglQueryDisplayAttribNV
GLEXT_API_CALL PFNEGLQUERYDMABUFFORMATSEXTPROC glext_eglQueryDmaBufFormatsEXT;
#define eglQueryDmaBufFormatsEXT glext_eglQueryDmaBufFormatsEXT
GLEXT_API_CALL PFNEGLQUERYDMABUFMODIFIERSEXTPROC
  glext_eglQueryDmaBufModifiersEXT;
#define eglQueryDmaBufModifiersEXT glext_eglQueryDmaBufModifiersEXT
GLEXT_API_CALL PFNEGLQUERYNATIVEDISPLAYNVPROC glext_eglQueryNativeDisplayNV;
#define eglQueryNativeDisplayNV glext_eglQueryNativeDisplayNV
GLEXT_API_CALL PFNEGLQUERYNATIVEPIXMAPNVPROC glext_eglQueryNativePixmapNV;
#define eglQueryNativePixmapNV glext_eglQueryNativePixmapNV
GLEXT_API_CALL PFNEGLQUERYNATIVEWINDOWNVPROC glext_eglQueryNativeWindowNV;
#define eglQueryNativeWindowNV glext_eglQueryNativeWindowNV
GLEXT_API_CALL PFNEGLQUERYOUTPUTLAYERATTRIBEXTPROC
  glext_eglQueryOutputLayerAttribEXT;
#define eglQueryOutputLayerAttribEXT glext_eglQueryOutputLayerAttribEXT
GLEXT_API_CALL PFNEGLQUERYOUTPUTLAYERSTRINGEXTPROC
  glext_eglQueryOutputLayerStringEXT;
#define eglQueryOutputLayerStringEXT glext_eglQueryOutputLayerStringEXT
GLEXT_API_CALL PFNEGLQUERYOUTPUTPORTATTRIBEXTPROC
  glext_eglQueryOutputPortAttribEXT;
#define eglQueryOutputPortAttribEXT glext_eglQueryOutputPortAttribEXT
GLEXT_API_CALL PFNEGLQUERYOUTPUTPORTSTRINGEXTPROC
  glext_eglQueryOutputPortStringEXT;
#define eglQueryOutputPortStringEXT glext_eglQueryOutputPortStringEXT
GLEXT_API_CALL PFNEGLQUERYSTREAMATTRIBKHRPROC glext_eglQueryStreamAttribKHR;
#define eglQueryStreamAttribKHR glext_eglQueryStreamAttribKHR
GLEXT_API_CALL PFNEGLQUERYSTREAMCONSUMEREVENTNVPROC
  glext_eglQueryStreamConsumerEventNV;
#define eglQueryStreamConsumerEventNV glext_eglQueryStreamConsumerEventNV
GLEXT_API_CALL PFNEGLQUERYSTREAMKHRPROC glext_eglQueryStreamKHR;
#define eglQueryStreamKHR glext_eglQueryStreamKHR
GLEXT_API_CALL PFNEGLQUERYSTREAMMETADATANVPROC glext_eglQueryStreamMetadataNV;
#define eglQueryStreamMetadataNV glext_eglQueryStreamMetadataNV
GLEXT_API_CALL PFNEGLQUERYSTREAMTIMEKHRPROC glext_eglQueryStreamTimeKHR;
#define eglQueryStreamTimeKHR glext_eglQueryStreamTimeKHR
GLEXT_API_CALL PFNEGLQUERYSTREAMU64KHRPROC glext_eglQueryStreamu64KHR;
#define eglQueryStreamu64KHR glext_eglQueryStreamu64KHR
GLEXT_API_CALL PFNEGLQUERYSTRINGPROC glext_eglQueryString;
#define eglQueryString glext_eglQueryString
GLEXT_API_CALL PFNEGLQUERYSUPPORTEDCOMPRESSIONRATESEXTPROC
  glext_eglQuerySupportedCompressionRatesEXT;
#define eglQuerySupportedCompressionRatesEXT                                  \
  glext_eglQuerySupportedCompressionRatesEXT
GLEXT_API_CALL PFNEGLQUERYSURFACEPROC glext_eglQuerySurface;
#define eglQuerySurface glext_eglQuerySurface
GLEXT_API_CALL PFNEGLQUERYSURFACE64KHRPROC glext_eglQuerySurface64KHR;
#define eglQuerySurface64KHR glext_eglQuerySurface64KHR
GLEXT_API_CALL PFNEGLQUERYSURFACEPOINTERANGLEPROC
  glext_eglQuerySurfacePointerANGLE;
#define eglQuerySurfacePointerANGLE glext_eglQuerySurfacePointerANGLE
GLEXT_API_CALL PFNEGLQUERYWAYLANDBUFFERWLPROC glext_eglQueryWaylandBufferWL;
#define eglQueryWaylandBufferWL glext_eglQueryWaylandBufferWL
GLEXT_API_CALL PFNEGLRELEASETEXIMAGEPROC glext_eglReleaseTexImage;
#define eglReleaseTexImage glext_eglReleaseTexImage
GLEXT_API_CALL PFNEGLRELEASETHREADPROC glext_eglReleaseThread;
#define eglReleaseThread glext_eglReleaseThread
GLEXT_API_CALL PFNEGLRESETSTREAMNVPROC glext_eglResetStreamNV;
#define eglResetStreamNV glext_eglResetStreamNV
GLEXT_API_CALL PFNEGLSETBLOBCACHEFUNCSANDROIDPROC
  glext_eglSetBlobCacheFuncsANDROID;
#define eglSetBlobCacheFuncsANDROID glext_eglSetBlobCacheFuncsANDROID
GLEXT_API_CALL PFNEGLSETDAMAGEREGIONKHRPROC glext_eglSetDamageRegionKHR;
#define eglSetDamageRegionKHR glext_eglSetDamageRegionKHR
GLEXT_API_CALL PFNEGLSETSTREAMATTRIBKHRPROC glext_eglSetStreamAttribKHR;
#define eglSetStreamAttribKHR glext_eglSetStreamAttribKHR
GLEXT_API_CALL PFNEGLSETSTREAMMETADATANVPROC glext_eglSetStreamMetadataNV;
#define eglSetStreamMetadataNV glext_eglSetStreamMetadataNV
GLEXT_API_CALL PFNEGLSIGNALSYNCKHRPROC glext_eglSignalSyncKHR;
#define eglSignalSyncKHR glext_eglSignalSyncKHR
GLEXT_API_CALL PFNEGLSIGNALSYNCNVPROC glext_eglSignalSyncNV;
#define eglSignalSyncNV glext_eglSignalSyncNV
GLEXT_API_CALL PFNEGLSTREAMACQUIREIMAGENVPROC glext_eglStreamAcquireImageNV;
#define eglStreamAcquireImageNV glext_eglStreamAcquireImageNV
GLEXT_API_CALL PFNEGLSTREAMATTRIBKHRPROC glext_eglStreamAttribKHR;
#define eglStreamAttribKHR glext_eglStreamAttribKHR
GLEXT_API_CALL PFNEGLSTREAMCONSUMERACQUIREATTRIBKHRPROC
  glext_eglStreamConsumerAcquireAttribKHR;
#define eglStreamConsumerAcquireAttribKHR                                     \
  glext_eglStreamConsumerAcquireAttribKHR
GLEXT_API_CALL PFNEGLSTREAMCONSUMERACQUIREKHRPROC
  glext_eglStreamConsumerAcquireKHR;
#define eglStreamConsumerAcquireKHR glext_eglStreamConsumerAcquireKHR
GLEXT_API_CALL PFNEGLSTREAMCONSUMERGLTEXTUREEXTERNALATTRIBSNVPROC
  glext_eglStreamConsumerGLTextureExternalAttribsNV;
#define eglStreamConsumerGLTextureExternalAttribsNV                           \
  glext_eglStreamConsumerGLTextureExternalAttribsNV
GLEXT_API_CALL PFNEGLSTREAMCONSUMERGLTEXTUREEXTERNALKHRPROC
  glext_eglStreamConsumerGLTextureExternalKHR;
#define eglStreamConsumerGLTextureExternalKHR                                 \
  glext_eglStreamConsumerGLTextureExternalKHR
GLEXT_API_CALL PFNEGLSTREAMCONSUMEROUTPUTEXTPROC
  glext_eglStreamConsumerOutputEXT;
#define eglStreamConsumerOutputEXT glext_eglStreamConsumerOutputEXT
GLEXT_API_CALL PFNEGLSTREAMCONSUMERRELEASEATTRIBKHRPROC
  glext_eglStreamConsumerReleaseAttribKHR;
#define eglStreamConsumerReleaseAttribKHR                                     \
  glext_eglStreamConsumerReleaseAttribKHR
GLEXT_API_CALL PFNEGLSTREAMCONSUMERRELEASEKHRPROC
  glext_eglStreamConsumerReleaseKHR;
#define eglStreamConsumerReleaseKHR glext_eglStreamConsumerReleaseKHR
GLEXT_API_CALL PFNEGLSTREAMFLUSHNVPROC glext_eglStreamFlushNV;
#define eglStreamFlushNV glext_eglStreamFlushNV
GLEXT_API_CALL PFNEGLSTREAMIMAGECONSUMERCONNECTNVPROC
  glext_eglStreamImageConsumerConnectNV;
#define eglStreamImageConsumerConnectNV glext_eglStreamImageConsumerConnectNV
GLEXT_API_CALL PFNEGLSTREAMRELEASEIMAGENVPROC glext_eglStreamReleaseImageNV;
#define eglStreamReleaseImageNV glext_eglStreamReleaseImageNV
GLEXT_API_CALL PFNEGLSURFACEATTRIBPROC glext_eglSurfaceAttrib;
#define eglSurfaceAttrib glext_eglSurfaceAttrib
GLEXT_API_CALL PFNEGLSWAPBUFFERSPROC glext_eglSwapBuffers;
#define eglSwapBuffers glext_eglSwapBuffers
GLEXT_API_CALL PFNEGLSWAPBUFFERSREGION2NOKPROC glext_eglSwapBuffersRegion2NOK;
#define eglSwapBuffersRegion2NOK glext_eglSwapBuffersRegion2NOK
GLEXT_API_CALL PFNEGLSWAPBUFFERSREGIONNOKPROC glext_eglSwapBuffersRegionNOK;
#define eglSwapBuffersRegionNOK glext_eglSwapBuffersRegionNOK
GLEXT_API_CALL PFNEGLSWAPBUFFERSWITHDAMAGEEXTPROC
  glext_eglSwapBuffersWithDamageEXT;
#define eglSwapBuffersWithDamageEXT glext_eglSwapBuffersWithDamageEXT
GLEXT_API_CALL PFNEGLSWAPBUFFERSWITHDAMAGEKHRPROC
  glext_eglSwapBuffersWithDamageKHR;
#define eglSwapBuffersWithDamageKHR glext_eglSwapBuffersWithDamageKHR
GLEXT_API_CALL PFNEGLSWAPINTERVALPROC glext_eglSwapInterval;
#define eglSwapInterval glext_eglSwapInterval
GLEXT_API_CALL PFNEGLTERMINATEPROC glext_eglTerminate;
#define eglTerminate glext_eglTerminate
GLEXT_API_CALL PFNEGLUNBINDWAYLANDDISPLAYWLPROC
  glext_eglUnbindWaylandDisplayWL;
#define eglUnbindWaylandDisplayWL glext_eglUnbindWaylandDisplayWL
GLEXT_API_CALL PFNEGLUNLOCKSURFACEKHRPROC glext_eglUnlockSurfaceKHR;
#define eglUnlockSurfaceKHR glext_eglUnlockSurfaceKHR
GLEXT_API_CALL PFNEGLUNSIGNALSYNCEXTPROC glext_eglUnsignalSyncEXT;
#define eglUnsignalSyncEXT glext_eglUnsignalSyncEXT
GLEXT_API_CALL PFNEGLWAITCLIENTPROC glext_eglWaitClient;
#define eglWaitClient glext_eglWaitClient
GLEXT_API_CALL PFNEGLWAITGLPROC glext_eglWaitGL;
#define eglWaitGL glext_eglWaitGL
GLEXT_API_CALL PFNEGLWAITNATIVEPROC glext_eglWaitNative;
#define eglWaitNative glext_eglWaitNative
GLEXT_API_CALL PFNEGLWAITSYNCPROC glext_eglWaitSync;
#define eglWaitSync glext_eglWaitSync
GLEXT_API_CALL PFNEGLWAITSYNCKHRPROC glext_eglWaitSyncKHR;
#define eglWaitSyncKHR glext_eglWaitSyncKHR

GLEXT_API_CALL int
glext_LoadEGLUserPtr (EGLDisplay display, GLEXTuserptrloadfunc load,
                      void* userptr);
GLEXT_API_CALL int
glext_LoadEGL (EGLDisplay display, GLEXTloadfunc load);

#ifdef GLEXT_EGL

GLEXT_API_CALL int
glext_LoaderLoadEGL (EGLDisplay display);

GLEXT_API_CALL void
glext_LoaderUnloadEGL (void);

#endif
#ifdef __cplusplus
}
#endif
#endif
